### ISSUE TITLE
Verifying MD5s.. seems stuck

### ISSUE THREAD

**Issue by DStrelak** [scipion-em/scipion-pyworkflow#119]
**Steps to reproduce**
```
./scipion3 test xmipp3.tests.test_protocols_xmipp_movies.TestEstimateGain
Scipion v3.0 () devel

Running tests....
Creating project at:  /home/david/ScipionUserData/projects/TestEstimateGain/project.sqlite
>>>> python3 /home/david/git/scipion3/scipion-pyworkflow/pyworkflow/apps/pw_sync_data.py --download movies 
Selected datasets: movies
Local copy of dataset movies detected.
Checking for updates...
Regenerating local MANIFEST...
Verifying MD5s..
```

**Problem**
What it actually does is to check the MD5, and download newer version. But user is not informed about it, so with slow connection, it behaves like if it got stuck.

**Expected**
MD5 verification should do only the MD5 hash comparison. If mismatch is detected, a list of files to be downloaded should be shown with proper progress indication

**Comment by pconesa** [comment]
Is this a logging issue? Are you saying that the downloading log line does
not happen?

**Comment by azazellochg** [comment]
"MD5 verification should do only the MD5 hash comparison. If mismatch is detected, a list of files to be downloaded should be shown with proper progress indication" - I think this is exactly what it already does now.  The long part is computing the hash for movies.

**Comment by DStrelak** [comment]
> Is this a logging issue? Are you saying that the downloading log line does not happen? 

That's right. I don't see any other output.

**Comment by DStrelak** [comment]
> "MD5 verification should do only the MD5 hash comparison. If mismatch is detected, a list of files to be downloaded should be shown with proper progress indication" - I think this is exactly what it already does now. The long part is computing the hash for movies.

From what I have seen, this is not the case. The CPU utilization was close to 0, but there was a download happening at the background.

**Comment by pconesa** [comment]
Maybe there is missing a log line or we need to flush the stdout. I'll check it out.

**Comment by pconesa** [comment]
I got it , the "Downloading ...." only happens in verbose mode...I'll change this.
