### ISSUE TITLE
wrong time for the protocol run

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-pyworkflow#127]
To reproduce:
1. Run a protocol with several steps
2. Stop/abort/fail at a certain step
3. Continue protocol 

When I hover the mouse over finished protocol box the Time is shown only for the last steps that were run after 3. It should be a sum of all steps

**Comment by pconesa** [comment]
@azazellochg , here I can see 2 interesting values:

A: elapsed time: date difference end-start
B: spent time: sum of all durations of the steps.

A will be inaccurate if a protocol fails and then is continued.
B will be similar to A is there are no parallel steps.

I think,  all the best we can fix now is to compute B, not sure if we can have A as well.

**Comment by azazellochg** [comment]
I agree with computing B now. For the future we could have: creation date, start date, end date, spent time (B). Don't think computing A makes much sense.

**Comment by pconesa** [comment]
I think we can have A and B, although A could be less informative in some cases but B too. So probably both can complement.

**Comment by pconesa** [comment]
This is implemented
