### ISSUE TITLE
Protocol Search Dialog now hides the top matching entries

### ISSUE THREAD

**Issue by delarosatrevin** [scipion-em/scipion-pyworkflow#134]
After the changes in the search dialog with the score,  now protocols with the highest scores are sometimes hidden in the crowd. I propose to changes that I think are easy to implement:
* Sort results by score by default
* Have a minimum score to be displayed (3 or above, because there are many of 1 of score that is not relevant)

What do you think @pconesa, @fonsecareyna82,  @azazellochg ?

**Comment by pconesa** [comment]
I think we've lost the sorting by score. Hidding them, I rather don't do it, since if is shown is cause there is a match somewhere.

I agree to rescue the sorting by score.

**Comment by delarosatrevin** [comment]
I think the score 1 is more of a false positive than a real match, but anyway, sorting will make this less important.

**Comment by pconesa** [comment]
This is addressed in #136
