### ISSUE TITLE
Do not update host.conf on scipion3 config --update?

### ISSUE THREAD

**Issue by pconesa** [scipion-em/scipion-pyworkflow#144]
This comes from one of our users:

> ad hosts.conf)
The first time setup it is good that it is generated.
When calling "scipion config --update" it would be more practical if you just validate it in memory and do not write back the new file without the #SBATCH comments.
Or you write it back inlcuding the # lines.
I think it would be enough if you print the validation error messages just to the screen so fixing/adapting the hosts.conf template can be an iterative process.

**Comment by azazellochg** [comment]
I'm ok with this change if "scipion config" will still generate host.conf when no such file exists :)

**Comment by pconesa** [comment]
It will, it should copy it and not parse it as before.
