### ISSUE TITLE
Scipion does not save class from 3dClassification

### ISSUE THREAD

**Issue by gilcantero** [scipion-em/scipion-pyworkflow#156]
When I clicked on the eye of "analyze results" to see the table with number of particles, slices, etc in the results of a 3D classification, the window was blocked for 15 minutes or so. I killed manually scipion from the console and when I try to visualize it, it opens but shows 0 as the number of particles for all the classes and I cannot save the particles of a certain class. I guess it has something to do with the database maybe? Is there any way to solve it?

Thanks,
David.

**Comment by pconesa** [comment]
Thanks @gilcantero 
Is this scipion2 (Diocletian) or 3?

**Comment by gilcantero** [comment]
scipion 2

**Comment by pconesa** [comment]
Is this a relion 3d classification?

**Comment by gilcantero** [comment]
yes, from relion

**Comment by gilcantero** [comment]
This is the output of the terminal when pressing the eye and the table appears:

java -Xmx20g -d64 -Djava.library.path=/home/virus/SOFTWARE/SCIPION/scipion2/software/em/xmipp/lib -Dplugins.dir=/home/virus/SOFTWARE/SCIPION/scipion2/software/em/xmipp/bindings/java/imagej/plugins -cp /usr/lib64/jvm/java-1.8.0-openjdk-1.8.0/lib/*:/home/virus/SOFTWARE/SCIPION/scipion2/software/em/xmipp/bindings/java/imagej/*:/home/virus/SOFTWARE/SCIPION/scipion2/software/em/xmipp/bindings/java/lib/* xmipp.viewer.scipion.ScipionViewer -i "Runs/030165_ProtRelionClassify3D/extra/relion_it022_classes_scipion.sqlite" --render _representative._filename --labels id _size --zoom 100 --visible enabled id _size _representative._filename _rlnclassDistribution _rlnAccuracyRotations _rlnAccuracyTranslations --sortby _size desc --order enabled id _size _representative._filename _rlnclassDistribution _rlnAccuracyRotations _rlnAccuracyTranslations --mode metadata --scipion 40643 30165 30146

**Comment by pconesa** [comment]
This is showing iteration 22,can you try to show iteration 21?

**Comment by gilcantero** [comment]
It arise thise error in a window:
Error: XMIPP_ERROR 36: Error in SQL of MetaData operations
Error accessing table code: 5 message:database is locked. SQL command SELECT name FROM sqlite_master WHERE type='table' LIMIT 1;
File: core/metadata_sql.cpp line: 1244


y esto en terminal:
java -Xmx20g -d64 -Djava.library.path=/home/virus/SOFTWARE/SCIPION/scipion2/soft            ware/em/xmipp/lib -Dplugins.dir=/home/virus/SOFTWARE/SCIPION/scipion2/software/e            m/xmipp/bindings/java/imagej/plugins -cp /usr/lib64/jvm/java-1.8.0-openjdk-1.8.0            /lib/*:/home/virus/SOFTWARE/SCIPION/scipion2/software/em/xmipp/bindings/java/ima            gej/*:/home/virus/SOFTWARE/SCIPION/scipion2/software/em/xmipp/bindings/java/lib/            * xmipp.viewer.scipion.ScipionViewer -i "Runs/030165_ProtRelionClassify3D/extra/            relion_it021_classes_scipion.sqlite" --render _representative._filename --labels             id _size --zoom 100 --visible enabled id _size _representative._filename _rlncl            assDistribution _rlnAccuracyRotations _rlnAccuracyTranslations --sortby _size de            sc --order enabled id _size _representative._filename _rlnclassDistribution _rln            AccuracyRotations _rlnAccuracyTranslations --mode metadata --scipion 48271 30165             30146
java.sql.SQLException: [SQLITE_BUSY]  The database file is locked (database is l            ocked)
        at org.sqlite.DB.newSQLException(DB.java:886)
        at org.sqlite.DB.newSQLException(DB.java:897)
        at org.sqlite.DB.throwex(DB.java:864)
        at org.sqlite.NativeDB.prepare(Native Method)
        at org.sqlite.DB.prepare(DB.java:207)
        at org.sqlite.Stmt.executeQuery(Stmt.java:186)
        at xmipp.viewer.scipion.ScipionMetaData.isScipionMetaData(ScipionMetaDat            a.java:1242)
        at xmipp.viewer.scipion.ScipionViewer.openFile(ScipionViewer.java:69)
        at xmipp.viewer.scipion.ScipionViewer.main(ScipionViewer.java:52)

**Comment by pconesa** [comment]
There is a db lock! 

Do you have enough space o the HD? (just in case)

**Comment by pconesa** [comment]
I think this can be closed. I do not think we will address this happening in Scipion2

**Comment by gilcantero** [comment]
Sin problema
