### ISSUE TITLE
Error when trying to save the workflow as JSON file

### ISSUE THREAD

**Issue by JuhaHuiskonen** [scipion-em/scipion-pyworkflow#158]
I select all the protocols and click export. When I try to save workflow.json I get an error

'NoneType' object has no attribute 'getObjId'

scipion v.3.0.5

**Comment by azazellochg** [comment]
Do you have a screenshot of the protocols you are trying to export? Would be interesting to see which protocol causes this..

**Comment by pconesa** [comment]
This is happening when a protocol has failed.
