### ISSUE TITLE
Error when the number of threads is the same of GPUs

### ISSUE THREAD

**Issue by delarosatrevin** [scipion-em/scipion-pyworkflow#159]
When trying to submit a STEP_PARALLEL protocol job and the number of threads is the same as the number of GPUs (usually should be greater or less, but this is a valid input anyway), it crashes when handling the gpuList from the executor code:

```
Traceback (most recent call last):
  File "/opt/cryoem/scipion/3.0.0/scipion-pyworkflow/pyworkflow/apps/pw_protocol_run.py", line 39, in <module>
    runProtocolMain(projPath, dbPath, protId)
  File "/opt/cryoem/scipion/3.0.0/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 2204, in runProtocolMain
    executor = ThreadStepExecutor(hostConfig, nThreads-1,
  File "/opt/cryoem/scipion/3.0.0/scipion-pyworkflow/pyworkflow/protocol/executor.py", line 178, in __init__
    self.gpuDict[node] = list(self.gpuList[i*chunk:(i+1)*chunk])
TypeError: slice indices must be integers or None or have an __index__ method
```
Example:
![image](https://user-images.githubusercontent.com/8441688/97286133-6ae1f200-1843-11eb-9aca-14ce2a6c5f06.png)

The same error happened with cryolo with the same threads/GPUs settings and I guess it will happen for any with this execution schema.

**Comment by pconesa** [comment]
Thanks @delarosatrevin . We'll find some time to fix this after the course.

**Comment by pconesa** [comment]
This has been fixed, probably here: https://github.com/scipion-em/scipion-pyworkflow/pull/203
