### ISSUE TITLE
Do not allow spaces, maybe other characters in the name of the project.

### ISSUE THREAD

**Issue by pconesa** [scipion-em/scipion-pyworkflow#170]
Yesterday in a remote course we had several case were 
 were creating  a project name with spaces.

This caused an error later on in Flexalign code. I know we could blame flexalign for this and I'll create an issue but here are my thoughts:

1.- Even if we fix flexalign.....will all work. I strongly doubt it.
2.- When this happens the error is far from giving a hint to the user that the problem is related with spaces in the name of the project. I'm  wondering how may users hit this and gave up?

I propose to  replace spaces by "_" or "-" or something else

Not sure if there are other problematic characters.

@delarosatrevin , @azazellochg ?

**Comment by azazellochg** [comment]
I think in ProtImportImages and in relion the spaces are simply stripped. I agree that in the project name they can be replaced by underscore. Does the dots in the name work?

**Comment by pconesa** [comment]
Not sure about the dots.
