### ISSUE TITLE
Installing RELION EM Plugins Issue

### ISSUE THREAD

**Issue by AlazzawiAdil** [scipion-em/scipion-pyworkflow#185]
Thanks in advance, recently I was using scipion and it does work perfectly. I got some issues while I tried to install RELION it keeps saying FAILED, any suggestions please ?

I did follow the installation using ubuntu with conda
I have posted a screenshot to what I had so far
![Screenshot from 2020-12-12 11-41-56](https://user-images.githubusercontent.com/38712332/101990987-47e29480-3c6f-11eb-8c4f-909d5c40c16d.png)

**Comment by azazellochg** [comment]
Hi @AlazzawiAdil , looks like a compilation problem. Could you please attach here two files: ScipionUserData/logs/Plugin*?

**Comment by azazellochg** [comment]
They should be in /home/adil/scipion3/ScipionUserDara/logs/. You can rename them so that their name ends with txt and attach to your message here (use drag and drop)

**Comment by AlazzawiAdil** [comment]
Thanks for your quick respond, actually I'm reinstalling right now I will post them upon I finished

**Comment by AlazzawiAdil** [comment]
Also I have a problem with the font I tried to follow the solution that you provide it in your website but unfortunately did not work either

**Comment by AlazzawiAdil** [comment]
Now I got this error 

MPI compilation failed. Check the INCDIRFLAGS, MPI_CXX and CXXFLAGS in 'xmipp.conf'
 In addition, MPI_CXXFLAGS can also be used to add flags to MPI compilations.'mpicxx --showme:compile' might help
 Cannot compile with MPI or use it
 rm xmipp_mpi_test_main*
 
Check failed! Something wrong with the configuration.

Traceback (most recent call last):
  File "/home/adil/EMAN2/envs/scipion3/lib/python3.8/site-packages/scipion/__main__.py", line 457, in <module>
    main()
  File "/home/adil/EMAN2/envs/scipion3/lib/python3.8/site-packages/scipion/__main__.py", line 297, in main
    installPluginMethods()
  File "/home/adil/EMAN2/envs/scipion3/lib/python3.8/site-packages/scipion/install/install_plugin.py", line 232, in installPluginMethods
    plugin.installBin({'args': ['-j', numberProcessor]})
  File "/home/adil/EMAN2/envs/scipion3/lib/python3.8/site-packages/scipion/install/plugin_funcs.py", line 166, in installBin
    environment.execute()
  File "/home/adil/EMAN2/envs/scipion3/lib/python3.8/site-packages/scipion/install/funcs.py", line 748, in execute
    self._executeTargets(targetList)
  File "/home/adil/EMAN2/envs/scipion3/lib/python3.8/site-packages/scipion/install/funcs.py", line 690, in _executeTargets
    tgt.execute()
  File "/home/adil/EMAN2/envs/scipion3/lib/python3.8/site-packages/scipion/install/funcs.py", line 221, in execute
    command.execute()
  File "/home/adil/EMAN2/envs/scipion3/lib/python3.8/site-packages/scipion/install/funcs.py", line 161, in execute
    assert glob(t), ("target '%s' not built (after "
AssertionError: target '/home/adil/scipion3/software/em/xmipp/bin/xmipp_reconstruct_significant' not built (after running 'cd . && ./xmipp config noAsk && ./xmipp check_config && ./xmipp compileAndInstall N=4 && ln -srfn build /home/adil/scipion3/software/em/xmipp && cd - && touch installation_finished && rm bindings_linked 2> /dev/null')
Error at main: target '/home/adil/scipion3/software/em/xmipp/bin/xmipp_reconstruct_significant' not built (after running 'cd . && ./xmipp config noAsk && ./xmipp check_config && ./xmipp compileAndInstall N=4 && ln -srfn build /home/adil/scipion3/software/em/xmipp && cd - && touch installation_finished && rm bindings_linked 2> /dev/null')


 _______________________________________________________________________________________ 
|                                                                                       |
| Installation failed                                                                   |
 _______________________________________________________________________________________ 

  Something went wrong (SEE ERRORS ABOVE) when running: 
  
   eval "$(/home/adil/EMAN2/bin/conda shell.bash hook)" &&
  conda activate scipion3 &&
  export SCIPION_HOME=/home/adil/scipion3 &&
  python -m scipion installp -p scipion-em-xmipp -j 4
   
  For more information about the installation errors that can appear when installing or 
  using Scipion go to: https://scipion-em.github.io/docs/docs/user/troubleshooting.html

**Comment by AlazzawiAdil** [comment]
I used exactly the following steps

sudo apt-get install gcc-8 g++-8 libopenmpi-dev make
conda activate
export CXX_CUDA=g++-8
export PATH=$PATH:/usr/local/cuda/bin
pip install --user scipion-installer
python -m scipioninstaller /home/adil/scipion3 -j 4

**Comment by azazellochg** [comment]
Hi, ok, that's a different issue now. It looks like you are using EMAN2 conda environment. You should avoid this by making sure you don't have EMAN2 sourced and your PATH and LD_LIBRARY_PATH are clean from other potentially conflicting programs.

**Comment by AlazzawiAdil** [comment]
thanks, you mean I have to delete EMAN2?

**Comment by azazellochg** [comment]
No, you need to make sure you do not have eman2 activated by default. E.g. remove "source /home/adil/EMAN2/etc/profile.d/conda.sh" from your ~/.bashrc

**Comment by AlazzawiAdil** [comment]
sorry for brothering you today, I really appreciate your help, how can I remove "source /home/adil/EMAN2/etc/profile.d/conda.sh" from your ~/.bashrc?

**Comment by azazellochg** [comment]
could you post here /home/adil/.bashrc file?

**Comment by AlazzawiAdil** [comment]
Thanks, I tried to find the file but it seems not founded.. that what I have so far
![Screenshot from 2020-12-12 13-26-35](https://user-images.githubusercontent.com/38712332/101993131-c34b4280-3c7d-11eb-9edc-c6927ad6f485.png)

**Comment by azazellochg** [comment]
Basically you need to comment out all lines that has eman2.

**Comment by azazellochg** [comment]
It's a hidden file, note the dot in the beginning: .bashrc

**Comment by azazellochg** [comment]
I see you also have relion folder. If you did install relion before there was no need to install binaries again in the Scipion plugin manager.

**Comment by AlazzawiAdil** [comment]
This is my bashrc file

# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# added by EMAN2 2.31 installer
# >>> conda init >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$(CONDA_REPORT_ERRORS=false '/home/adil/EMAN2/bin/conda' shell.bash hook 2> /dev/null)"
if [ $? -eq 0 ]; then
    \eval "$__conda_setup"
else
    if [ -f "/home/adil/EMAN2/etc/profile.d/conda.sh" ]; then
# . "/home/adil/EMAN2/etc/profile.d/conda.sh"  # commented out by conda initialize
        CONDA_CHANGEPS1=false conda activate base
    else
        \export PATH="/home/adil/EMAN2/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda init <<<

# added by EMAN2 2.31 installer
# >>> conda init >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$(CONDA_REPORT_ERRORS=false '/home/adil/EMAN2/bin/conda' shell.bash hook 2> /dev/null)"
if [ $? -eq 0 ]; then
    \eval "$__conda_setup"
else
    if [ -f "/home/adil/EMAN2/etc/profile.d/conda.sh" ]; then
# . "/home/adil/EMAN2/etc/profile.d/conda.sh"  # commented out by conda initialize
        CONDA_CHANGEPS1=false conda activate base
    else
        \export PATH="/home/adil/EMAN2/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda init <<<

# added by EMAN2 2.31 installer
# >>> conda init >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$(CONDA_REPORT_ERRORS=false '/home/adil/EMAN2/bin/conda' shell.bash hook 2> /dev/null)"
if [ $? -eq 0 ]; then
    \eval "$__conda_setup"
else
    if [ -f "/home/adil/EMAN2/etc/profile.d/conda.sh" ]; then
# . "/home/adil/EMAN2/etc/profile.d/conda.sh"  # commented out by conda initialize
        CONDA_CHANGEPS1=false conda activate base
    else
        \export PATH="/home/adil/EMAN2/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda init <<<

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/adil/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/adil/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/home/adil/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/adil/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<


# added by EMAN2 2.31 installer
# >>> conda init >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$(CONDA_REPORT_ERRORS=false '/home/adil/EMAN2/bin/conda' shell.bash hook 2> /dev/null)"
if [ $? -eq 0 ]; then
    \eval "$__conda_setup"
else
    if [ -f "/home/adil/EMAN2/etc/profile.d/conda.sh" ]; then
        . "/home/adil/EMAN2/etc/profile.d/conda.sh"
        CONDA_CHANGEPS1=false conda activate base
    else
        \export PATH="/home/adil/EMAN2/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda init <<<

**Comment by AlazzawiAdil** [comment]
RELION is not working in my machine for this reason I tried to used it through sciption I was using it before and it was working perfectly but after I installed EMAN 2 I got some issues as I said before

**Comment by azazellochg** [comment]
gosh, looks like you have installed eman2 four times...

Please remove all lines from the first occurrence of "# added by EMAN2 2.31 installer". Create two new files in your home folder
**eman2.rc**
```
# added by EMAN2 2.31 installer
# >>> conda init >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$(CONDA_REPORT_ERRORS=false '/home/adil/EMAN2/bin/conda' shell.bash hook 2> /dev/null)"
if [ $? -eq 0 ]; then
    \eval "$__conda_setup"
else
    if [ -f "/home/adil/EMAN2/etc/profile.d/conda.sh" ]; then
        . "/home/adil/EMAN2/etc/profile.d/conda.sh"
        CONDA_CHANGEPS1=false conda activate base
    else
        \export PATH="/home/adil/EMAN2/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda init <<<
```

and **conda.rc**
```
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/adil/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/adil/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/home/adil/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/adil/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
```

When you need  to use eman, just type: **source eman2.rc**. When you need conda, type **source conda.rc**
Open new terminal window and then source conda.rc. Then install scipion as documented.

**Comment by azazellochg** [comment]
>  it was working perfectly but after I installed EMAN 2 I got some issues as I said before
A lot of programs will conflict with eman if you do not separate it's activation as I described above (creating eman2.rc).

**Comment by AlazzawiAdil** [comment]
Thanks a lot I will do that

**Comment by AlazzawiAdil** [comment]
Hi @azazellochg thanks for your instructions they are very helpfull, I did everything and now EMAN 2 has been sperated in difieract activation file as you described I did install scipion sucssusfilly but again when I tried to install RELION I got the same error I have listed the two files that you asked me before 

First the Plugin file looks like:

Collecting scipion-em-relion==3.0.0b7
  Using cached scipion_em_relion-3.0.0b7-py3-none-any.whl (250 kB)
Requirement already satisfied: scipion-em in ./anaconda3/envs/scipion3/lib/python3.8/site-packages (from scipion-em-relion==3.0.0b7) (3.0.6)
Requirement already satisfied: emtable in ./anaconda3/envs/scipion3/lib/python3.8/site-packages (from scipion-em-relion==3.0.0b7) (0.0.7)
Requirement already satisfied: biopython==1.76 in ./anaconda3/envs/scipion3/lib/python3.8/site-packages (from scipion-em->scipion-em-relion==3.0.0b7) (1.76)
Requirement already satisfied: scipion-pyworkflow in ./anaconda3/envs/scipion3/lib/python3.8/site-packages (from scipion-em->scipion-em-relion==3.0.0b7) (3.0.8)
Requirement already satisfied: numpy in ./anaconda3/envs/scipion3/lib/python3.8/site-packages (from biopython==1.76->scipion-em->scipion-em-relion==3.0.0b7) (1.18.4)
Requirement already satisfied: psutil<=5.7.0 in ./anaconda3/envs/scipion3/lib/python3.8/site-packages (from scipion-pyworkflow->scipion-em->scipion-em-relion==3.0.0b7) (5.7.0)
Requirement already satisfied: requests<=2.23.0 in ./anaconda3/envs/scipion3/lib/python3.8/site-packages (from scipion-pyworkflow->scipion-em->scipion-em-relion==3.0.0b7) (2.23.0)
Requirement already satisfied: bibtexparser<=1.2.0 in ./anaconda3/envs/scipion3/lib/python3.8/site-packages (from scipion-pyworkflow->scipion-em->scipion-em-relion==3.0.0b7) (1.2.0)
Requirement already satisfied: matplotlib<=3.2.2 in ./anaconda3/envs/scipion3/lib/python3.8/site-packages (from scipion-pyworkflow->scipion-em->scipion-em-relion==3.0.0b7) (3.2.2)
Requirement already satisfied: configparser<=5.0.0 in ./anaconda3/envs/scipion3/lib/python3.8/site-packages (from scipion-pyworkflow->scipion-em->scipion-em-relion==3.0.0b7) (5.0.0)
Requirement already satisfied: numpy in ./anaconda3/envs/scipion3/lib/python3.8/site-packages (from biopython==1.76->scipion-em->scipion-em-relion==3.0.0b7) (1.18.4)
Requirement already satisfied: pillow<=7.1.2 in ./anaconda3/envs/scipion3/lib/python3.8/site-packages (from scipion-pyworkflow->scipion-em->scipion-em-relion==3.0.0b7) (7.1.2)
Requirement already satisfied: future>=0.16.0 in ./anaconda3/envs/scipion3/lib/python3.8/site-packages (from bibtexparser<=1.2.0->scipion-pyworkflow->scipion-em->scipion-em-relion==3.0.0b7) (0.18.2)
Requirement already satisfied: pyparsing>=2.0.3 in ./anaconda3/envs/scipion3/lib/python3.8/site-packages (from bibtexparser<=1.2.0->scipion-pyworkflow->scipion-em->scipion-em-relion==3.0.0b7) (2.4.7)
Requirement already satisfied: pyparsing>=2.0.3 in ./anaconda3/envs/scipion3/lib/python3.8/site-packages (from bibtexparser<=1.2.0->scipion-pyworkflow->scipion-em->scipion-em-relion==3.0.0b7) (2.4.7)
Requirement already satisfied: numpy in ./anaconda3/envs/scipion3/lib/python3.8/site-packages (from biopython==1.76->scipion-em->scipion-em-relion==3.0.0b7) (1.18.4)
Requirement already satisfied: kiwisolver>=1.0.1 in ./anaconda3/envs/scipion3/lib/python3.8/site-packages (from matplotlib<=3.2.2->scipion-pyworkflow->scipion-em->scipion-em-relion==3.0.0b7) (1.3.1)
Requirement already satisfied: cycler>=0.10 in ./anaconda3/envs/scipion3/lib/python3.8/site-packages (from matplotlib<=3.2.2->scipion-pyworkflow->scipion-em->scipion-em-relion==3.0.0b7) (0.10.0)
Requirement already satisfied: python-dateutil>=2.1 in ./anaconda3/envs/scipion3/lib/python3.8/site-packages (from matplotlib<=3.2.2->scipion-pyworkflow->scipion-em->scipion-em-relion==3.0.0b7) (2.8.1)
Requirement already satisfied: six in ./anaconda3/envs/scipion3/lib/python3.8/site-packages (from cycler>=0.10->matplotlib<=3.2.2->scipion-pyworkflow->scipion-em->scipion-em-relion==3.0.0b7) (1.15.0)
Requirement already satisfied: six in ./anaconda3/envs/scipion3/lib/python3.8/site-packages (from cycler>=0.10->matplotlib<=3.2.2->scipion-pyworkflow->scipion-em->scipion-em-relion==3.0.0b7) (1.15.0)
Requirement already satisfied: chardet<4,>=3.0.2 in ./anaconda3/envs/scipion3/lib/python3.8/site-packages (from requests<=2.23.0->scipion-pyworkflow->scipion-em->scipion-em-relion==3.0.0b7) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./anaconda3/envs/scipion3/lib/python3.8/site-packages (from requests<=2.23.0->scipion-pyworkflow->scipion-em->scipion-em-relion==3.0.0b7) (1.25.11)
Requirement already satisfied: certifi>=2017.4.17 in ./anaconda3/envs/scipion3/lib/python3.8/site-packages (from requests<=2.23.0->scipion-pyworkflow->scipion-em->scipion-em-relion==3.0.0b7) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in ./anaconda3/envs/scipion3/lib/python3.8/site-packages (from requests<=2.23.0->scipion-pyworkflow->scipion-em->scipion-em-relion==3.0.0b7) (2.10)
Installing collected packages: scipion-em-relion
Successfully installed scipion-em-relion-3.0.0b7
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- BUILD TYPE set to the default type:  'Release'
-- Setting fallback CUDA_ARCH=35
-- ALLOW_CTF_IN_SAGD enabled - This build of RELION allows modulation of particle images by a contrast transfer function inside stochastic average gradient descent, as specified in Claim 1 of patent US10,282,513B2
-- CUDA enabled - Building CUDA-accelerated version of RELION
-- Setting cpu precision to double
-- Setting accelerated code precision to single
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "10.2") 
-- Using cuda wrapper to compile....
-- Cuda version is >= 7.5 and single-precision build, enable double usage warning.
-- Omitting GUI targets as per your request
-- Found MPI_C: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so (found version "3.1") 
-- Found MPI_CXX: /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- MPI_INCLUDE_PATH : /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi;/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent;/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent/include;/usr/lib/x86_64-linux-gnu/openmpi/include
-- MPI_LIBRARIES : /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so;/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so
-- MPI_CXX_INCLUDE_PATH : /usr/lib/x86_64-linux-gnu/openmpi/include/openmpi;/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent;/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent/include;/usr/lib/x86_64-linux-gnu/openmpi/include
-- MPI_CXX_LIBRARIES : /usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi_cxx.so;/usr/lib/x86_64-linux-gnu/openmpi/lib/libmpi.so
-- CMAKE_C_COMPILER : /usr/bin/cc
-- CMAKE_CXX_COMPILER : /usr/bin/c++
-- MPI_C_COMPILER : /usr/bin/mpicc
-- MPI_CXX_COMPILER : /usr/bin/mpicxx
-- CMAKE_CXX_COMPILER_ID : GNU
-- CMAKE_C_COMPILER : /usr/bin/mpicc
-- CMAKE_CXX_COMPILER : /usr/bin/mpicxx
-- MPI_C_COMPILER : /usr/bin/mpicc
-- MPI_CXX_COMPILER : /usr/bin/mpicxx
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Found FFTW
-- FFTW_PATH: /usr/include
-- FFTW_INCLUDES: /usr/include
-- FFTW_LIBRARIES: /usr/lib/x86_64-linux-gnu/libfftw3f.so;/usr/lib/x86_64-linux-gnu/libfftw3.so
-- Looking for sincos
-- Looking for sincos - found
-- Looking for __sincos
-- Looking for __sincos - not found
-- Found TIFF: /usr/lib/x86_64-linux-gnu/libtiff.so (found version "4.0.9") 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.6.34") 
-- Building static libs (larger build size and binaries)
-- CMAKE_BINARY_DIR:/home/adil/scipion3/software/em/relion-3.1.0
-- Git commit ID: 
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Configuring incomplete, errors occurred!
See also "/home/adil/scipion3/software/em/relion-3.1.0/CMakeFiles/CMakeOutput.log".
See also "/home/adil/scipion3/software/em/relion-3.1.0/CMakeFiles/CMakeError.log".
2020-12-12 16:50:56,162 INFO:  [31mError executing the operation: install scipion-em-relion[0m
[32mBuilding scipion-em-relion ...[0m
[36m/home/adil/anaconda3/envs/scipion3/bin/python -m pip install scipion-em-relion==3.0.0b7[0m
[32mDone (0.82 seconds)[0m
[32mBuilding relion-3.1.0 ...[0m
  Skipping command: [36mwget -nv -c -O /home/adil/scipion3/software/em/relion-3.1.0.tgz.part https://github.com/3dem/relion/archive/3.1.0.tar.gz
mv -v /home/adil/scipion3/software/em/relion-3.1.0.tgz.part /home/adil/scipion3/software/em/relion-3.1.0.tgz[0m
  All targets exist.
[36mcd /home/adil/scipion3/software/em[0m
[36mtar -xf relion-3.1.0.tgz[0m
[36mcd /home/adil/scipion3/software/em/relion-3.1.0[0m
[36mcmake -DGUI=OFF -DCMAKE_INSTALL_PREFIX=./ .[0m
[36mcd /home/adil/scipion3/software/em/relion-3.1.0[0m
[36mmake -j 4[0m

Second the Plugin (error)

BUILD_SHARED_LIBS = OFF
Running apps/CMakeLists.txt...
CMake Error: File /home/adil/.git/packed-refs does not exist.
CMake Error at src/apps/CMakeFiles/git-data/grabRef.cmake:27 (configure_file):
  configure_file Problem configuring file
Call Stack (most recent call first):
  cmake/GetGitRevisionDescription.cmake:83 (include)
  src/apps/CMakeLists.txt:21 (get_git_head_revision)


CMake Error at src/apps/CMakeFiles/git-data/grabRef.cmake:28 (file):
  file failed to open for reading (No such file or directory):

    /home/adil/scipion3/software/em/relion-3.1.0/src/apps/CMakeFiles/git-data/packed-refs
Call Stack (most recent call first):
  cmake/GetGitRevisionDescription.cmake:83 (include)
  src/apps/CMakeLists.txt:21 (get_git_head_revision)


CMake Error at src/apps/CMakeFiles/git-data/grabRef.cmake:39 (file):
  file failed to open for reading (No such file or directory):

    /home/adil/scipion3/software/em/relion-3.1.0/src/apps/CMakeFiles/git-data/head-ref
Call Stack (most recent call first):
  cmake/GetGitRevisionDescription.cmake:83 (include)
  src/apps/CMakeLists.txt:21 (get_git_head_revision)


CMake Error at src/apps/CMakeLists.txt:22 (string):
  string sub-command SUBSTRING requires four arguments.


make: *** No targets specified and no makefile found.  Stop.
2020-12-12 16:50:56,163 ERROR:  [31mError executing the operation: install scipion-em-relion[0m


I really appreciate your help and time... :)

**Comment by azazellochg** [comment]
Hm, have you tried removing completely /home/adil/scipion3/software/em/relion-3.1.0 folder and trying again? Also. does your separate relion installation work? If yes, you do not need to install binaries again in scipion, just make a link to existing relion

**Comment by AlazzawiAdil** [comment]
I did remove it and my sperate RELION does not work for this reason I tried to install it through scipion, do want me to remove it again and install it and see?

**Comment by AlazzawiAdil** [comment]
I did remove  /home/adil/scipion3/software/em/relion-3.1.0 and tried to install it again through the plug manager and it still FAILD

**Comment by azazellochg** [comment]
I see, unfortunately I've never seen this error. The relion provided with scipion is not the latest version, have you tried installing relion 3.1.1 separately according to [official relion guide](https://www3.mrc-lmb.cam.ac.uk/relion/index.php/Download_%26_install)? If that fails, you might want to report it on https://github.com/3dem/relion/issues

**Comment by AlazzawiAdil** [comment]
ok thanks, could you check in your machine if the RELION does install successfully that I know I have an issue in my machine, I really appreciate that.

**Comment by azazellochg** [comment]
I am not using plugin manager, but a separate standalone installation.

**Comment by AlazzawiAdil** [comment]
may I tried that to see if I'm able to use it? if you don't mind?

**Comment by AlazzawiAdil** [comment]
I mean you guide me to that?

**Comment by AlazzawiAdil** [comment]
I have installed other programs and all been installed correctly except RELION

**Comment by azazellochg** [comment]
I mentioned the link to the relion website above, it has all the
instructions on how to install it

**Comment by AlazzawiAdil** [comment]
I did follow the instructions that are provided in the link too and got it installed correctly but when I tried the GUI does not work my question is about the Edit the environment set-up what should I do to it?

**Comment by azazellochg** [comment]
If the gui doesn't work then it did not install correctly. You can ask
relion developers for help on ccpem mailing list or relion github
