### ISSUE TITLE
Project names not displayed properly

### ISSUE THREAD

**Issue by JuhaHuiskonen** [scipion-em/scipion-pyworkflow#187]
After updating to 3.0.7, the main Scipion window does not show project names correctly.  Has the scaling of the fonts or they way fonts are used changed somehow?

<img width="629" alt="Screenshot 2020-12-13 at 17 22 08" src="https://user-images.githubusercontent.com/20352352/102016107-dcc8b900-3d67-11eb-9684-1a27f803a6a4.png">

**Comment by azazellochg** [comment]
wow... it was ok in 3.0.6 @JuhaHuiskonen ? @pconesa the only changes in 3.0.7 were https://github.com/scipion-em/scipion-pyworkflow/compare/v3.0.6...v3.0.7

**Comment by JuhaHuiskonen** [comment]
Yes it was ok in 3.0.6. If I change the window size, I get the top most project name to appear. The rest are invisible. Other fonts are fine, e.g. when I open a project.

**Comment by JuhaHuiskonen** [comment]
OK, I have restarted my NoMachine connection and the issue with the fonts has disappeared.

**Comment by pconesa** [comment]
Thank you both. Better this way because there wasn't any change that, to my knowledge, would have affected the fonts.
