### ISSUE TITLE
error: implicit declaration of function 'resize_configs_are_equal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]

### ISSUE THREAD

**Issue by FraaaMazzz** [scipion-em/scipion-pyworkflow#188]
I am attempting at installing Scipion 2 on my MacOS Catalina. (I haven't found any instructions on how to get Scipion 3 for Mac only for Ubuntu and CentOS)

I am now stuck in the installation step after launching:
./scipion install -j 5
 
I get the following error:
Error: target '/Users/francesca/Scipion/scipion/software/lib/libhdf5_cpp.dylib' not built (after running 'make install > /Users/francesca/Scipion/scipion/software/log/hdf5_make_install.log 2>&1')

This is the hdf5_make_install.log file.

Making install in src
 ../bin/install-sh -c -d '/Users/francesca/Scipion/scipion/software/lib'
 /bin/sh ../libtool   --mode=install /usr/bin//install -c   libhdf5.la '/Users/francesca/Scipion/scipion/software/lib'
libtool: install: /usr/bin//install -c .libs/libhdf5.9.dylib /Users/francesca/Scipion/scipion/software/lib/libhdf5.9.dylib
libtool: install: (cd /Users/francesca/Scipion/scipion/software/lib && { ln -s -f libhdf5.9.dylib libhdf5.dylib || { rm -f libhdf5.dylib && ln -s libhdf5.9.dylib libhdf5.dylib; }; })
libtool: install: /usr/bin//install -c .libs/libhdf5.lai /Users/francesca/Scipion/scipion/software/lib/libhdf5.la
libtool: install: /usr/bin//install -c .libs/libhdf5.a /Users/francesca/Scipion/scipion/software/lib/libhdf5.a
libtool: install: chmod 644 /Users/francesca/Scipion/scipion/software/lib/libhdf5.a
libtool: install: ranlib /Users/francesca/Scipion/scipion/software/lib/libhdf5.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /Users/francesca/Scipion/scipion/software/lib/libhdf5.a(H5CS.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /Users/francesca/Scipion/scipion/software/lib/libhdf5.a(H5Dmpio.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /Users/francesca/Scipion/scipion/software/lib/libhdf5.a(H5Fmpi.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /Users/francesca/Scipion/scipion/software/lib/libhdf5.a(H5FDdirect.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /Users/francesca/Scipion/scipion/software/lib/libhdf5.a(H5FDmpi.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /Users/francesca/Scipion/scipion/software/lib/libhdf5.a(H5FDmpio.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /Users/francesca/Scipion/scipion/software/lib/libhdf5.a(H5MFdbg.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /Users/francesca/Scipion/scipion/software/lib/libhdf5.a(H5Obogus.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /Users/francesca/Scipion/scipion/software/lib/libhdf5.a(H5Smpio.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /Users/francesca/Scipion/scipion/software/lib/libhdf5.a(H5TS.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /Users/francesca/Scipion/scipion/software/lib/libhdf5.a(H5Zszip.o) has no symbols
 ../bin/install-sh -c -d '/Users/francesca/Scipion/scipion/software/include'
 /usr/bin//install -c -m 644 hdf5.h H5api_adpt.h H5overflow.h H5pubconf.h H5public.h H5version.h H5Apublic.h H5ACpublic.h H5Cpublic.h H5Dpublic.h H5Epubgen.h H5Epublic.h H5Fpublic.h H5FDpublic.h H5FDcore.h H5FDdirect.h H5FDfamily.h H5FDlog.h H5FDmpi.h H5FDmpio.h H5FDmulti.h H5FDsec2.h H5FDstdio.h H5Gpublic.h H5Ipublic.h H5Lpublic.h H5MMpublic.h H5Opublic.h H5Ppublic.h H5PLextern.h H5Rpublic.h H5Spublic.h H5Tpublic.h H5Zpublic.h '/Users/francesca/Scipion/scipion/software/include'
 ../bin/install-sh -c -d '/Users/francesca/Scipion/scipion/software/lib'
 /usr/bin//install -c -m 644 libhdf5.settings '/Users/francesca/Scipion/scipion/software/lib'
Making install in test
  CCLD     libh5test.la
  CCLD     testhdf5
  CCLD     lheap
  CCLD     ohdr
  CCLD     stab
  CCLD     gheap
  CC       cache.o
cache.c:29:1: warning: '/*' within block comment [-Wcomment]
/* private typedef declarations: */
^
cache.c:25754:23: error: implicit declaration of function 'resize_configs_are_equal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        } else if ( ! resize_configs_are_equal(&test_auto_size_ctl, \
                      ^
cache.c:25826:23: error: implicit declaration of function 'resize_configs_are_equal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        } else if ( ! resize_configs_are_equal(&test_auto_size_ctl, \
                      ^
cache.c:25901:23: error: implicit declaration of function 'resize_configs_are_equal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        } else if ( ! resize_configs_are_equal(&test_auto_size_ctl, \
                      ^
cache.c:25977:23: error: implicit declaration of function 'resize_configs_are_equal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        } else if ( ! resize_configs_are_equal(&test_auto_size_ctl, \
                      ^
cache.c:26050:23: error: implicit declaration of function 'resize_configs_are_equal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        } else if ( ! resize_configs_are_equal(&test_auto_size_ctl, \
                      ^
cache.c:26125:23: error: implicit declaration of function 'resize_configs_are_equal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        } else if ( ! resize_configs_are_equal(&test_auto_size_ctl, \
                      ^
cache.c:26197:23: error: implicit declaration of function 'resize_configs_are_equal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        } else if ( ! resize_configs_are_equal(&test_auto_size_ctl, \
                      ^
cache.c:26273:23: error: implicit declaration of function 'resize_configs_are_equal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        } else if ( ! resize_configs_are_equal(&test_auto_size_ctl, \
                      ^
cache.c:26345:23: error: implicit declaration of function 'resize_configs_are_equal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        } else if ( ! resize_configs_are_equal(&test_auto_size_ctl, \
                      ^
cache.c:26417:23: error: implicit declaration of function 'resize_configs_are_equal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        } else if ( ! resize_configs_are_equal(&test_auto_size_ctl, \
                      ^
cache.c:26492:23: error: implicit declaration of function 'resize_configs_are_equal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        } else if ( ! resize_configs_are_equal(&test_auto_size_ctl, \
                      ^
cache.c:26564:23: error: implicit declaration of function 'resize_configs_are_equal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        } else if ( ! resize_configs_are_equal(&test_auto_size_ctl, \
                      ^
cache.c:26640:23: error: implicit declaration of function 'resize_configs_are_equal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        } else if ( ! resize_configs_are_equal(&test_auto_size_ctl, \
                      ^
cache.c:26713:23: error: implicit declaration of function 'resize_configs_are_equal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        } else if ( ! resize_configs_are_equal(&test_auto_size_ctl, \
                      ^
cache.c:26788:23: error: implicit declaration of function 'resize_configs_are_equal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        } else if ( ! resize_configs_are_equal(&test_auto_size_ctl, \
                      ^
cache.c:26860:23: error: implicit declaration of function 'resize_configs_are_equal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        } else if ( ! resize_configs_are_equal(&test_auto_size_ctl, \
                      ^
cache.c:26932:23: error: implicit declaration of function 'resize_configs_are_equal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        } else if ( ! resize_configs_are_equal(&test_auto_size_ctl, \
                      ^
cache.c:27008:23: error: implicit declaration of function 'resize_configs_are_equal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        } else if ( ! resize_configs_are_equal(&test_auto_size_ctl, \
                      ^
cache.c:27083:23: error: implicit declaration of function 'resize_configs_are_equal' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        } else if ( ! resize_configs_are_equal(&test_auto_size_ctl, \
                      ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.
make[1]: *** [cache.o] Error 1
make: *** [install-recursive] Error 1

I found other people having the "implicit declaration of function" error but I am not able to solve this. 

Can you help me solve this?

**Comment by pconesa** [comment]
Hi @FraaaMazzz , we currently do not support Mac fro Scipion 2 or Scipion3.

Actually, Scipion3 (plain) could be installed in a MAC machine using conda and avoiding xmipp installation like:

`python -m scipioninstaller /path/where/you/want/scipion -noXmipp`

But without xmipp you'll not be able to do much cryoem stuff.

There are developers that the do not need xmipp that were able to develop a plugin on a Mac.

Can I aks you, what is your purpose?

**Comment by FraaaMazzz** [comment]
Hello!

Thank you for your reply! 
> python -m scipioninstaller /path/where/you/want/scipion -noXmipp
> 

I have tried this now and it has been downloaded. Thank you!

The error message I posted comes when installing Scipion 2
Following the instruction at these links:
https://github.com/I2PC/scipion/wiki/Installing-on-Mac
https://github.com/I2PC/scipion/wiki/How-to-Install
> Can I aks you, what is your purpose?
> 

I am a new PhD student and I am just getting started with CryoEM. 
Is there a way to get Xmipp for Mac?
If not, could you suggest some way to overcome this problem? Get a virtual machine for Ubuntu? Or are there some things I can modify? Unfortunately I don’t have much experience with coding but maybe you could point me towards someone I could contact someone who could help me out.

Kind regards,
Francesca

**Comment by pconesa** [comment]
Well, a linux virtual machine should work, but for most cryoem projects your are going to need a GPU, space,RAM and CPUs as much as possible. A virtual machine will not help, even a laptop (I guess iswhat you have) is far from ideal.

EIther request access to a cluster where scipion can be installed in your institution, or get a proper cryoem workstation with 1 or 2 GPUs.

**Comment by FraaaMazzz** [comment]
Ok, this helps! 
I am working on getting access to the cluster!
So what do I have to install on my laptop to work on the cluster?
