### ISSUE TITLE
mpi troubles

### ISSUE THREAD

**Issue by rmarabini** [scipion-em/scipion-pyworkflow#189]
I describe in the following a feature of the protocols executed using mpirun (at least in my machine).  I have a  machine with 16  cores.  I am using a protocol that uses mpi (8 cores). If a lunch two copies of the same protocol  the second protocol uses  the same 8 cores that were utilized earlier. Searching in the literature it seems that this is the expected behavior of  mpirun (see https://stackoverflow.com/questions/47784610/how-to-use-mpirun-to-use-different-cpu-cores-for-different-programs)  and that the "correct" command to send the process is

mpirun --cpu-set 0-7 --bind-to core -n  8 ...
mpirun --cpu-set 8-15 --bind-to core -n  8  ...

where 8-15 are the cores to be used. In scipion it is easy to modify the mpirun command and set it to "mpirun --bind-to core" but the cpu numbers need to be given by the user. So the question is. Could somebody modify the form so it is possible to supply the parameters needed by --cpu-set

**Comment by azazellochg** [comment]
This is solved by "mpirun -bind-to none ..."

**Comment by rmarabini** [comment]
That is:

1) edit the file hosts.conf usually available in scipionpath/config directory
2) search for PARALLEL_COMMAND 
3) set it to       mpirun  --bind-to none -np %_(JOB_NODES)d %_(COMMAND)s

the actual value may be different in your box.

**Comment by pconesa** [comment]
Close?

**Comment by rmarabini** [comment]
yes please.
