### ISSUE TITLE
Analyze real big project load performance with GUI.

### ISSUE THREAD

**Issue by pconesa** [scipion-em/scipion-pyworkflow#200]

**Comment by azazellochg** [comment]
What does big mean? A lot of protocols or a lot of sets or a lot of items in sets

**Comment by pconesa** [comment]
I think items in the sets should not affect the project load. But we'll see if I'm wrong. For now big means number of protocols.

**Comment by azazellochg** [comment]
wow, so many sprints! what is the summary for this issue? Has it improved after all the fixes in performance branch?

**Comment by fonsecareyna82** [comment]
https://docs.google.com/spreadsheets/d/1sC6jCBurNvLIxwF0N_4-aJiM-grUIa9Ixi2ZfMjmqy4/edit#gid=0
https://docs.google.com/presentation/d/1_I-pnO0i7kcXBByqBDRMIW28IXjVi2ZviDAtWzOcylo/edit#slide=id.g9c5c5ebc3c_0_18
