### ISSUE TITLE
whole tmp folder is removed 

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-pyworkflow#212]
After the protocol is finished.
That breaks a lot of viewers, as they do not expect the folder missing and they are not suppossed to create it.

https://github.com/scipion-em/scipion-pyworkflow/blob/3dc54f6d920f018caec99192bfec039a54764b06/pyworkflow/protocol/protocol.py#L1318

**Comment by azazellochg** [comment]
I understand that if tmp is a link to ssd cache then it makes sense to remove it completely. Should we keep the folder (but remove its content) if it is not a link? This would mean I have to go through all plugins and check that none of them writes to tmp

**Comment by pconesa** [comment]
So, what will do the viewer if tmp is gone, cause using ssd?

**Comment by pconesa** [comment]
We have been modifying many viewers already, and usually is just using either: system tmp folder or prot.getExtra()

**Comment by azazellochg** [comment]
okay, I'll do that.
