### ISSUE TITLE
protocol tree view always expanded

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-pyworkflow#218]
I'm using devel branch for all core plugins. In the left protocol tree (e.g. View SPA) all subtrees are fully expanded even if I collapse them and reopen Scipion. This was not the case before, I believe it's stored in settings.sqlite?

**Comment by pconesa** [comment]
I don't think this was ever implemented. I testes on scipion2 and it doesn't either remember the "collapse" status. settings.sqlite is used for labels, box positions but not the tree.

**Comment by azazellochg** [comment]
I create a new project in scipion2:
![Screenshot_20210318_135015](https://user-images.githubusercontent.com/6952870/111637558-71bcd180-87f1-11eb-9af9-ee0b7d04ae89.png)

I create a new peoject in scipion3:
![Screenshot_20210318_135252](https://user-images.githubusercontent.com/6952870/111637613-826d4780-87f1-11eb-93f2-8f5cf36f6397.png)

So essentially now all views are expanded by default from start.

**Comment by azazellochg** [comment]
PS. Also it would be nice to set the font size for the left tree, e.g. with a config variable. For me it looks too crowded and small

**Comment by pconesa** [comment]
Ok, probably the difference is that Scipion2 didn't expand the tree further than the "c" level. We can rescue that behaviour. I've tested and I can confirm that the "extension status" of the tree is not kept in any of the versions.

Scipion 2 and 3 always show the tree that same way after a reopen, Scipion 2 partially expanded, Scipion3 fully expanded.

**Comment by pconesa** [comment]
By the way, font size can the set in a variable:

SCIPION_FONT_SIZE, default value is 10.

**Comment by azazellochg** [comment]
Great!

**Comment by azazellochg** [comment]
> Ok, probably the difference is that Scipion2 didn't expand the tree further than the "c" level. We can rescue that behaviour. I've tested and I can confirm that the "extension status" of the tree is not kept in any of the versions.
> 
> Scipion 2 and 3 always show the tree that same way after a reopen, Scipion 2 partially expanded, Scipion3 fully expanded.

I see. I remembered this because in Scipion 2 "Movies" section was never expanded :)
