### ISSUE TITLE
getToc renamed but not replaced in pw_run_tests (and other places?)

### ISSUE THREAD

**Issue by delarosatrevin** [scipion-em/scipion-pyworkflow#224]
Bug introduced here: https://github.com/scipion-em/scipion-pyworkflow/commit/1e058ac7121a469a59eddcc97b0b44a43d045546

**Comment by delarosatrevin** [comment]
Not only the name was changed... but also the return type :(

**Comment by pconesa** [comment]
Thanks! I'll fix that
