### ISSUE TITLE
Xmipp Installation Issue, Possible Nvidia Driver Issue?

### ISSUE THREAD

**Issue by JustasR1** [scipion-em/scipion-pyworkflow#236]
Hello,

I'm trying to install scipion for some specialized cryo processing, and ran into some issues installing Xmipp. I was able to install scipion using miniconda and the -noXmipp option. However, when I try to run the plugin manager to install Xmipp, I get the below issue:

```
00001:   Traceback (most recent call last):
00002:     File "./xmipp", line 1794, in <module>
00003:       configDict = config()
00004:     File "./xmipp", line 1151, in config
00005:       configCuda(new_config_dict)
00006:     File "./xmipp", line 942, in configCuda
00007:       nvccVersion, nvccFullVersion = getCudaVersion(nvcc)
00008:     File "./xmipp", line 1655, in getCudaVersion
00009:       nvccVersion = float(str(tokens[0] + '.' + tokens[1]))
00010:   ValueError: could not convert string to float: 'Build cuda_11.1'
00011:   2021-04-13 14:08:47,349 ERROR:  Error executing the operation: install scipion-em-xmipp
```

This seems to be a cuda error, which actually makes a lot of sense seeing as we've had a number of other odd issues with this system (ie. can't run certain Cryosparc jobs at the same time on separate GPU's, some crashes and other issues while running different cryo programs). Am I reading this right that this is an issue with cuda, and if so, what troubleshooting should I do to install Xmipp (besides a re-installation of cuda)?

Best,
Justas

**Comment by azazellochg** [comment]
Hi @pconesa who is now responsible for xmipp installation?

**Comment by dmaluenda** [comment]
Hi @JustasR1,

Despite the error is triggered due to a quite silly thing, the main problem is Xmipp is not supporting cuda 11, yet. Indeed, we are working on supporting it, but it's not ready, yet.

A workaround can be found by installing cuda10 and using it to compile and run Xmipp.

To install cuda10, please check nvidia webpage. Then localize where cuda10 is installed (usually in `/usr/local/cuda10`).

To set it for xmipp, there is two possibilities.

1. If <SCIPION_HOME>/config/scipion.conf exists, edit it to add
```
XMIPP_CUDA_BIN=/usr/local/cuda10/bin
XMIPP_CUDA_LIB=/usr/local/cuda10/lib
```
  and try again. If not exist, you can create it with just this two lines.

2. Alternativelly, without editing the config file, you can run the following
```
export XMIPP_CUDA_BIN=/usr/local/cuda10/bin
export XMIPP_CUDA_LIB=/usr/local/cuda10/lib
scipion3 installp -p scipion-em-xmipp
```
check your cuda-bin and cuda-lib paths.

**Comment by JustasR1** [comment]
Hi David,

Thank you for the response, I just got xmipp installed without issue using Cuda 10.0.

Best,
Justas

From: David Maluenda Niubó ***@***.***>
Date: Wednesday, April 14, 2021 at 4:21 AM
To: scipion-em/scipion-pyworkflow ***@***.***>
Cc: Rodarte, Justas V ***@***.***>, Mention ***@***.***>
Subject: Re: [scipion-em/scipion-pyworkflow] Xmipp Installation Issue, Possible Nvidia Driver Issue? (#236)

Hi @JustasR1<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_JustasR1&d=DwMCaQ&c=eRAMFD45gAfqt84VtBcfhQ&r=dFvFJX5sHRsUBJKImx2V5A9YiXfLtbd74YGjtYoLJBA&m=EGEWgxSxUOQrn35fsODqA3V0tfykVXUTmW2HagGOphk&s=R4BJuSEQai7AkRpqG3EyT0wNcszaP7MGQ-4cPlG4T0g&e=>,

Despite the error is triggered due to a quite silly thing, the main problem is Xmipp is not supporting cuda 11, yet. Indeed, we are working on supporting it, but it's not ready, yet.

A workaround can be found by installing cuda10 and using it to compile and run Xmipp.

To install cuda10, please check nvidia webpage. Then localize where cuda10 is installed (usually in /usr/local/cuda10).

To set it for xmipp, there is two possibilities.

  1.  If <SCIPION_HOME>/config/scipion.conf exists, edit it to add

XMIPP_CUDA_BIN=/usr/local/cuda10/bin

XMIPP_CUDA_LIB=/usr/local/cuda10/lib

and try again. If not exist, you can create it with just this two lines.

  1.  Alternativelly, without editing the config file, you can run the following

export XMIPP_CUDA_BIN=/usr/local/cuda10/bin

export XMIPP_CUDA_LIB=/usr/local/cuda10/lib

scipion3 installp -p scipion-em-xmipp

check your cuda-bin and cuda-lib paths.
