### ISSUE TITLE
mpi4py is not in requirements

### ISSUE THREAD

**Issue by rmarabini** [scipion-em/scipion-pyworkflow#253]
mpi4py is used in pw_protocol_mpirun.py (and in several plugins) but it is not installed by scipion. That is, the user needs to install it by hand. I suggest to add in "requirements.txt"     mpi4py>=3.0.3

**Comment by pconesa** [comment]
Thanks @rmarabini rmarabini .

If @delarosatrevin agrees I'm happy to add mpi4py.

**Comment by delarosatrevin** [comment]
I will take a look at it.

**Comment by delarosatrevin** [comment]
Hum...yes, it is a requirement right now. So I guess we should add to requirement.txt. I know that we have discussed it but I can't remember the reasons why we did not add it in the first place.

**Comment by pconesa** [comment]
I'll add it then.

**Comment by rmarabini** [comment]
Hi @pconesa,

   Is this done? Can we close this issue?
