### ISSUE TITLE
Install plugin deepLearningToolkit-0.2 meet a err

### ISSUE THREAD

**Issue by shuaishuairuirui** [scipion-em/scipion-pyworkflow#263]
Hi scipion team,

When I install the deeplearning Toolkit meet a err like blew.Other program runs fine.Only the job PARTICLE CONSEUSE have a problem.Can you give me some help?My os is ubuntu 20.04.Thanks.

/bin/sh: 1: update: not found
00002:   Exception in thread plugin-manager:
00003:   Traceback (most recent call last):
00004:     File "/home/shuaishuai/anaconda3/envs/scipion3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
00005:       self.run()
00006:     File "/home/shuaishuai/anaconda3/envs/scipion3/lib/python3.8/threading.py", line 870, in run
00007:       self._target(*self._args, **self._kwargs)
00008:     File "/home/shuaishuai/anaconda3/envs/scipion3/lib/python3.8/site-packages/scipion/install/plugin_manager.py", line 769, in _applyOperations
00009:       self.reloadInstalledPlugin(op.getObjParent())
00010:     File "/home/shuaishuai/anaconda3/envs/scipion3/lib/python3.8/site-packages/scipion/install/plugin_manager.py", line 922, in reloadInstalledPlugin
00011:       self.tree.insert(pluginName, "end",
00012:     File "/home/shuaishuai/anaconda3/envs/scipion3/lib/python3.8/site-packages/scipion/install/plugin_manager.py", line 124, in insert
00013:       ttk.Treeview.insert(self, parent, index, iid, **kw)
00014:     File "/home/shuaishuai/anaconda3/envs/scipion3/lib/python3.8/tkinter/ttk.py", line 1361, in insert
00015:       res = self.tk.call(self._w, "insert", parent, index,
00016:   _tkinter.TclError: Item deepLearningToolkit-0.2[scipion-em-xmipp] already exists

**Comment by fonsecareyna82** [comment]
Hi @shuaishuairuirui,
Perhaps with the command: "scipion3 update"  fixes this problem.
Otherwise, could you make a picture of the output that these commands will print from the command line?
scipion3 installp --help
scipion3 installb --help

I want to know the plugins and binaries you have installed to try to reproduce the error.

**Comment by shuaishuairuirui** [comment]
Hi @fonsecareyna82 ,

Thanks very much for your reply.I had using the command update.The command didn't fix the problem.The other command output is blew.If you need any other information,I will do it as soon as possible.I stiil have the plugin manage loading problem as before asking.And I only can loading the plugin when I shuttdown my station.And start at first few minutes I can loading the plugin manage.May this problem connect with this problem.I don't know.

[Screenshot from 2021-06-10 18-42-11](https://user-images.githubusercontent.com/59869039/121512283-21ce5f00-ca1c-11eb-9eb2-93d80def0c57.png)
![Screenshot from 2021-06-10 18-42-18](https://user-images.githubusercontent.com/59869039/121512290-23982280-ca1c-11eb-9cb4-a8cd9c30584c.png)

**Comment by shuaishuairuirui** [comment]
> Hi @fonsecareyna82 ,
> 
> Thanks very much for your reply.I had using the command update.The command didn't fix the problem.The other command output is blew.If you need any other information,I will do it as soon as possible.I stiil have the plugin manage loading problem as before asking.And I only can loading the plugin when I shuttdown my station.And start at first few minutes I can loading the plugin manage.May this problem connect with this problem.I don't know.
> 
> [Screenshot from 2021-06-10 18-42-11](https://user-images.githubusercontent.com/59869039/121512283-21ce5f00-ca1c-11eb-9eb2-93d80def0c57.png)
> ![Screenshot from 2021-06-10 18-42-18](https://user-images.githubusercontent.com/59869039/121512290-23982280-ca1c-11eb-9cb4-a8cd9c30584c.png)

![Screenshot from 2021-06-10 18-42-11](https://user-images.githubusercontent.com/59869039/121513159-1c254900-ca1d-11eb-9670-7b51657df117.png)

**Comment by shuaishuairuirui** [comment]
> Hi @shuaishuairuirui,
> Perhaps with the command: "scipion3 update" fixes this problem.
> Otherwise, could you make a picture of the output that these commands will print from the command line?
> scipion3 installp --help
> scipion3 installb --help
> 
> I want to know the plugins and binaries you have installed to try to reproduce the error.

Hi @fonsecareyna82 ,

Can you give me the best strategy to install scipion include the OS,CUDA,driver,plugins.I will reinstall my OS so that I can use scipion as soon as possible.Thanks very much.

shuaishuai

**Comment by pconesa** [comment]
Try this  and send the output if it does not work.


scipion3 installb deepLearningToolkit

This is another way to install binaries without the plugin manager.

**Comment by shuaishuairuirui** [comment]
Hi @pconesa ,

Thanks very much for your reply.Blew is the output of the command.This seems didn't have err.But when I run deep particles consensus will get err.

Scipion v3.0.7 - Eugenius
Building deepLearningToolkit-0.2 ...
  Skipping command: wget -nv -c -O /home/shuaishuai/software/scipion/software/em/deepLearningToolkit.tgz.part http://scipion.cnb.csic.es/downloads/scipion/software/external/deepLearningToolkit.tgz
mv -v /home/shuaishuai/software/scipion/software/em/deepLearningToolkit.tgz.part /home/shuaishuai/software/scipion/software/em/deepLearningToolkit.tgz
  All targets exist.
  Skipping command: tar -xf deepLearningToolkit.tgz
  All targets exist.
cd /home/shuaishuai/software/scipion/software/em/deepLearningToolkit
if ls /home/shuaishuai/software/scipion/software/em/xmipp/lib/libXmipp.so > /dev/null ; then touch xmippLibToken; echo ' > CUDA support find. Driver version: 460' ; else echo ; echo ' > Xmipp installation not found, please install it first (xmippSrc or xmippBin*).';echo; fi
 > CUDA support find. Driver version: 460
  Skipping command: export PYTHONPATH="" && eval "$(/home/shuaishuai/anaconda3/bin/conda shell.bash hook)" && conda create --force --yes -n xmipp_DLTK_v0.3 python=3 pandas=0.23 scikit-image=0.14 opencv=3.4 tensorflow-gpu=1.15 keras=2.2 scikit-learn=0.22  -c anaconda && conda activate xmipp_DLTK_v0.3 && pip install numpy==1.18.4 numpy==1.18.4 && conda env export > xmipp_DLTK_v0.3.yml
  All targets exist.
  Skipping command: export PYTHONPATH="" && eval "$(/home/shuaishuai/anaconda3/bin/conda shell.bash hook)" && conda create --force --yes -n xmipp_MicCleaner python=3.6 micrograph-cleaner-em=0.35  -c rsanchez1369 -c anaconda -c conda-forge && conda activate xmipp_MicCleaner && conda env export > xmipp_MicCleaner.yml
  All targets exist.
  Skipping command: export PYTHONPATH="" && eval "$(/home/shuaishuai/anaconda3/bin/conda shell.bash hook)" && conda create --force --yes -n xmipp_deepEMhancer python=3.6 deepemhancer=0.12 numba=0.45  -c rsanchez1369 -c anaconda -c conda-forge && conda activate xmipp_deepEMhancer && conda env export > xmipp_deepEMhancer.yml
  All targets exist.
cd /home/shuaishuai/software/scipion/software/em/deepLearningToolkit
rm models_UPDATED_on_* xmippLibToken 2>/dev/null ; echo 'Downloading pre-trained models...' ; /home/shuaishuai/software/scipion/software/em/xmipp/bin/xmipp_sync_data update /home/shuaishuai/software/scipion/software/em/xmipp/models http://scipion.cnb.csic.es/downloads/scipion/software/em DLmodels && touch models_UPDATED_on_11_6_2021 && echo ' > Tensorflow installed with CUDA SUPPORT.'
Downloading pre-trained models...
Verifying MD5s...
 14%...
...done. Updated files: 0
Uncompressing models: cat /home/shuaishuai/software/scipion/software/em/xmipp/models/xmipp_model_*.tgz | tar xzf - -i --directory=/home/shuaishuai/software/scipion/software/em/xmipp/models
 > Tensorflow installed with CUDA SUPPORT.
cd /home/shuaishuai/software/scipion/software/em/
Link 'deepLearningToolkit-0.2 -> deepLearningToolkit'
Created link: 'deepLearningToolkit-0.2 -> deepLearningToolkit'
Done (34.93 seconds)

**Comment by shuaishuairuirui** [comment]
The job err output of deep consensus picking:

File 'Runs/013707_XmippProtScreenDeepConsensus/logs/run.stdout' doesn't existFile 'Runs/013707_XmippProtScreenDeepConsensus/logs/run.stdout' doesn't exist00001:   RUNNING PROTOCOL -----------------
00002:   Hostname: shuaishuai-Super-Server
00003:   PID: 8274
00004:   pyworkflow: 3.0.14
00005:   plugin: xmipp3
00006:   currentDir: /home/shuaishuai/ScipionUserData/projects/old
00007:   workingDir: Runs/013707_XmippProtScreenDeepConsensus
00008:   runMode: Continue
00009:             MPI: 1
00010:         threads: 2
00011:    Starting at step: 1
00012:    Running steps 
00013:   STARTED: initializeStep, step 1, time 2021-06-11 20:58:40.354481
00014:   FINISHED: initializeStep, step 1, time 2021-06-11 20:58:40.764141
00015:   STARTED: preprocessMicsStep, step 2, time 2021-06-11 20:58:40.766276
00016:    xmipp_preprocess_mics -i Runs/013707_XmippProtScreenDeepConsensus/tmp/preprocMic_inputs.txt -s 0.495 -d 2.34375 -o Runs/013707_XmippProtScreenDeepConsensus/tmp/preProcMics -t 2 --invert_contrast
00017:   WARNING: This is xmipp_base implementation for script
00018:   [Parallel(n_jobs=2)]: Using backend MultiprocessingBackend with 2 concurrent workers.
00019:   Traceback (most recent call last):
00020:     File "/home/shuaishuai/anaconda3/envs/scipion3/lib/python3.8/site-packages/joblib/parallel.py", line 820, in dispatch_one_batch
00021:       tasks = self._ready_batches.get(block=False)
00022:     File "/home/shuaishuai/anaconda3/envs/scipion3/lib/python3.8/queue.py", line 167, in get
00023:       raise Empty
00024:   _queue.Empty
00025:   
00026:   During handling of the above exception, another exception occurred:
00027:   
00028:   Traceback (most recent call last):
00029:     File "/home/shuaishuai/software/scipion/software/bindings/xmipp_base.py", line 107, in tryRun
00030:       self.run()
00031:     File "/home/shuaishuai/software/scipion/software/em/xmipp/bin/xmipp_preprocess_mics", line 97, in run
00032:       Parallel(n_jobs= numberOfThreads, backend="multiprocessing", verbose=1)(
00033:     File "/home/shuaishuai/anaconda3/envs/scipion3/lib/python3.8/site-packages/joblib/parallel.py", line 1041, in __call__
00034:       if self.dispatch_one_batch(iterator):
00035:     File "/home/shuaishuai/anaconda3/envs/scipion3/lib/python3.8/site-packages/joblib/parallel.py", line 831, in dispatch_one_batch
00036:       islice = list(itertools.islice(iterator, big_batch_size))
00037:     File "/home/shuaishuai/software/scipion/software/em/xmipp/bin/xmipp_preprocess_mics", line 98, in <genexpr>
00038:       delayed(preproOneMic, check_pickle=False)(*arg) for arg in argsList)
00039:   TypeError: delayed() got an unexpected keyword argument 'check_pickle'
00040:   Traceback (most recent call last):
00041:     File "/home/shuaishuai/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 197, in run
00042:       self._run()
00043:     File "/home/shuaishuai/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 248, in _run
00044:       resultFiles = self._runFunc()
00045:     File "/home/shuaishuai/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 244, in _runFunc
00046:       return self._func(*self._args)
00047:     File "/home/shuaishuai/anaconda3/envs/scipion3/lib/python3.8/site-packages/xmipp3/protocols/protocol_screen_deepConsensus.py", line 775, in preprocessMicsStep
00048:       self.runJob('xmipp_preprocess_mics', args, numberOfMpi=1)
00049:     File "/home/shuaishuai/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 1388, in runJob
00050:       self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
00051:     File "/home/shuaishuai/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/protocol/executor.py", line 65, in runJob
00052:       process.runJob(log, programName, params,
00053:     File "/home/shuaishuai/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/utils/process.py", line 52, in runJob
00054:       return runCommand(command, env, cwd)
00055:     File "/home/shuaishuai/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/utils/process.py", line 67, in runCommand
00056:       check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr,
00057:     File "/home/shuaishuai/anaconda3/envs/scipion3/lib/python3.8/subprocess.py", line 364, in check_call
00058:       raise CalledProcessError(retcode, cmd)
00059:   subprocess.CalledProcessError: Command ' xmipp_preprocess_mics -i Runs/013707_XmippProtScreenDeepConsensus/tmp/preprocMic_inputs.txt -s 0.495 -d 2.34375 -o Runs/013707_XmippProtScreenDeepConsensus/tmp/preProcMics -t 2 --invert_contrast' returned non-zero exit status 1.
00060:   Protocol failed: Command ' xmipp_preprocess_mics -i Runs/013707_XmippProtScreenDeepConsensus/tmp/preprocMic_inputs.txt -s 0.495 -d 2.34375 -o Runs/013707_XmippProtScreenDeepConsensus/tmp/preProcMics -t 2 --invert_contrast' returned non-zero exit status 1.
00061:   FAILED: preprocessMicsStep, step 2, time 2021-06-11 20:58:41.173259
00062:   *** Last status is failed 
00063:   ------------------- PROTOCOL FAILED (DONE 2/16)

**Comment by DStrelak** [comment]
> Can you give me the best strategy to install scipion include the OS,CUDA,driver,plugins.

Please refer to the documentation: https://scipion-em.github.io/docs/docs/scipion-modes/how-to-install.html
As for the OS, I can recommend you some LTS version of Ubuntu (20.04).
Additional dependencies for Xmipp are these: 
`sudo apt-get -y install scons libsqlite3-dev libhdf5-dev libopencv-dev scons libfftw3-dev libopenmpi-dev openmpi-bin python3-numpy python3-dev libtiff5-dev`
For Cuda, please refer to their installation guide: https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#ubuntu-installation 
We recommend you version 10.2 or newer.

**Comment by DStrelak** [comment]
So this problem seems to be related to bad / missing installation of Xmipp. 
Please let us know if you managed to install Scipion from scratch as I recommended you in the other ticket.
If you still experience issues, feel free to reopen this ticket.

**Comment by shuaishuairuirui** [comment]
> So this problem seems to be related to bad / missing installation of Xmipp.
> Please let us know if you managed to install Scipion from scratch as I recommended you in the other ticket.
> If you still experience issues, feel free to reopen this ticket.

Hi @DStrelak ,

Thanks for you reply.I have done some things to solve this problem.It all fail with the same err,I also try install using -dev.They all failed.(Reinstall my os 20.04 in two different machine.One's GPU is rtx8000.Another is 1080.One cuda10.1.Another cuda10.2.I don't if I can using cuda11.If could I will install scipion in 3090.).Maybe this is a bug?

/bin/sh: 1: update: not found

This very strange.I don't know the "update" is which library.What kind of dependencies I should install.Can you give some help.Thanks 

shuaishuai

**Comment by DStrelak** [comment]
Hi @shuaishuairuirui 
I'm sorry to hear that you still experience some issues.
However, without providing us with additional information, as requested in the other ticket, we are unable to help you.
Please send us the complete log from the installation process.

**Comment by shuaishuairuirui** [comment]
Hi @DStrelak 

Thanks for your reply.The log I have send to the email address scipion@cnb.csic.es from 'csjb18@mails.tsinghua.edu.cn'.Any other request you  also can tell me.

shuaishuai
