### ISSUE TITLE
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.

### ISSUE THREAD

**Issue by aseedb** [scipion-em/scipion-pyworkflow#280]
Hi, 
On our HPC cluster we need to activate conda using 
`eval "$(conda shell.bash hook)"`

I have set CONDA_ACTIVATION_COMMAND to this like that:
`export CONDA_ACTIVATION_CMD="eval \"\$(conda shell.bash hook)\""
`
when I run `echo $CONDA_ACTIVATION_CMD ` I am getting this output:
`eval "$(conda shell.bash hook)"`

When I then run `python -m scipioninstaller local/scipion/ -j 4` I am getting in some places of the output the following error:
   
    CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
    To initialize your shell, run
  
     $ conda init <SHELL_NAME>
     ...

I have attached the whole output 
[scipioninstall_output.txt](https://github.com/scipion-em/scipion-pyworkflow/files/6829916/scipioninstall_output.txt)

To test out what was going wrong I added an echo statement to the variable:
`export CONDA_ACTIVATION_CMD="echo \"ACTIVATION CMD USED\" ; eval \"\$(conda shell.bash hook)\""`

It seems that the activation command is only used in some places where conda is activated but not all and hence we get the errors. See output 
[scipioninstall_output2.txt](https://github.com/scipion-em/scipion-pyworkflow/files/6830004/scipioninstall_output2.txt)

At the end compilation failed. I am not sure if this is linked with the issue described above though.

One more note. 
To use conda I need to activate the respective modules like so:
`module load CUDA/10.1.243 Anaconda3 GCC
`
I have also added this to the variable: 
` export CONDA_ACTIVATION_CMD="module load CUDA\/10.1.243 Anaconda3 GCC ; echo \"ACTIVATION CMD USED\" ; eval \"\$(conda shell.bash hook)\""` but it did not help.

**Comment by azazellochg** [comment]
Hi @aseedb ,

I think you can ignore the conda error (for now, during install) as I can see from the logs the packages get installed inside scipion3 env anyway.

There are two errors:
1) Headers for 'libhdf5' not found at '/storage/homefs/bzuber/.conda/envs/scipion3/include'. No alternative found in the system.
This means you need to have libhdf5-dev on your cluster
2)  No valid compiler found. Skipping CUDA compilation. This means nvcc is not found. It's fine if you do not want to use Xmipp GPU programs.

**Comment by aseedb** [comment]
Hi @azazellochg 
Thanks for your quick reply! 

1. I'll check with the cluster managers if they can install libhdf5-dev. I found the libraries but not the headers indeed.
2. Regarding CUDA, in my environment I can run nvcc. However, it seems that it is not visible to the installation script. I then set CXX_CUDA to my nvcc. Then the next error arises, nvcc fatal   : Unknown option '-fPIC'. I'll also check it with the cluster managers.

**Comment by azazellochg** [comment]
Hi @aseedb , we are currently updating installation instructions (https://github.com/scipion-em/docs/blob/release-3.0.0/docs/scipion-modes/how-to-install.rst).

Since usually the libraries locations are very specific on any cluster, I would suggest to :
1) edit xmipp.conf (it is in /path/to/scipion/software/em/xmipp/xmipp.conf), following [xmipp guide](https://github.com/I2PC/xmipp/wiki/Xmipp-configuration-(version-20.07))
2) export XMIPP_NOCONFIG=True (so that this config is not overwritten)
3) /path/for/scipion/scipion3 installp -p scipion-em-xmipp -j 12 (recompile xmipp)

**Comment by aseedb** [comment]
@azazellochg, excellent. I will look into it.
