### ISSUE TITLE
how to share scipion environment with other users

### ISSUE THREAD

**Issue by chenzhao-CZ** [scipion-em/scipion-pyworkflow#310]
I am sorry that I haven't used conda very often,. If I install scipion using conda as the administrator, how can I share the scipion environment with other users? I have tried a couple of things I found online and none of them worked. Thank you very much for your help!

Best,
Chen

**Comment by azazellochg** [comment]
Hello Chen,

I'm sorry nobody has replied to you yet. Conda does not require root permission for installation, so as long as your users have read access to the folder with the scipion environment then can activate and use it

**Comment by pconesa** [comment]
Look at this reply: it may help.
https://stackoverflow.com/a/48928772/3157958

**Comment by pconesa** [comment]
Or this one:https://conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html

**Comment by pconesa** [comment]
More precisely here: https://conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#specify-env-directories
