### ISSUE TITLE
error using protocol xmipp3-highres

### ISSUE THREAD

**Issue by thibaut1998e** [scipion-em/scipion-pyworkflow#322]
Hi, I got an error using the protocol xmipp3-highres, I can't figure out what is wrong.
Summary of the protcols launched : 
![image](https://user-images.githubusercontent.com/58691353/148068303-befcbfdd-3fca-4c34-b5c1-da137090fbf5.png)

I first imported the particle using the protocol 'import averages'. (I didn't need to do the picking since I work with simulated data). Here are the imported particles : 
![image](https://user-images.githubusercontent.com/58691353/148073307-c03d36b5-5daa-450c-9554-6286d193980f.png)

Then I used the protocol ransac to get an initial volume initialization. I set these parameters : 
![image](https://user-images.githubusercontent.com/58691353/148073464-a5eeb5a9-bc69-4591-9f9f-a58a52db18ec.png)
The protocol ransac returned 10 output volumes, I created a subset of two output volumes, as it is required for the protocol 'xmipp3-highres'. 
Then I launched the protocol 'xmipp3-highres' with this parameters 
![image](https://user-images.githubusercontent.com/58691353/148073965-38888337-4088-43ea-bbca-18149cc12f38.png)

(I didn't change the parameters of the other tabs).

And I got the error : 

File 'Runs/002085_XmippProtReconstructHighRes/logs/run.stdout' doesn't existFile 'Runs/002085_XmippProtReconstructHighRes/logs/run.stdout' doesn't exist00001:   Logging configured. STDOUT --> Runs/002085_XmippProtReconstructHighRes/logs/run.stdout , STDERR --> Runs/002085_XmippProtReconstructHighRes/logs/run.stderr
00002:   RUNNING PROTOCOL -----------------
00003:   Protocol starts
00004:   Hostname: langlang
00005:   PID: 1452659
00006:   pyworkflow: 3.0.17
00007:   plugin: xmipp3
00008:   currentDir: /home/eloy/ScipionUserData/projects/reconstruct_from_2D_projection
00009:   workingDir: Runs/002085_XmippProtReconstructHighRes
00010:   runMode: Continue
00011:             MPI: 8
00012:         threads: 1
00013:    Starting at step: 1
00014:    Running steps 
00015:   STARTED: convertInputStep, step 1, time 2022-01-04 15:33:25.934372
00016:    xmipp_metadata_utilities -i Runs/002085_XmippProtReconstructHighRes/extra/images.xmd --fill image1 constant noImage
00017:    xmipp_metadata_utilities -i Runs/002085_XmippProtReconstructHighRes/extra/images.xmd --operate modify_values "image1=image"
00018:    xmipp_metadata_utilities -i Runs/002085_XmippProtReconstructHighRes/extra/images.xmd --fill particleId constant 1
00019:    xmipp_metadata_utilities -i Runs/002085_XmippProtReconstructHighRes/extra/images.xmd --operate modify_values "particleId=itemId"
00020:    xmipp_metadata_utilities -i Runs/002085_XmippProtReconstructHighRes/extra/images.xmd --operate keep_column particleId -o Runs/002085_XmippProtReconstructHighRes/extra/imagesId.xmd
00021:   FINISHED: convertInputStep, step 1, time 2022-01-04 15:33:26.071478
00022:   STARTED: doIteration000, step 2, time 2022-01-04 15:33:26.079022
00023:    xmipp_metadata_split -i Runs/002085_XmippProtReconstructHighRes/extra/images.xmd --oroot Runs/002085_XmippProtReconstructHighRes/extra/Iter000/images -n 2
00024:   Protocol failed: local variable 'fnVol1' referenced before assignment
00025:   FAILED: doIteration000, step 2, time 2022-01-04 15:33:26.116126
00026:   *** Last status is failed 
00027:   ------------------- PROTOCOL FAILED (DONE 2/24)

**Comment by cossorzano** [comment]
Dear Eric,

highres is mostly meant to refine a single volume. Instead of passing a SetOfVolumes try to pass a single Volume. That should work.

Kind regards, Carlos Oscar

**Comment by pconesa** [comment]
Did this worked?
