### ISSUE TITLE
Xmipp3 Cant Align Particles Imported from Relion 4 

### ISSUE THREAD

**Issue by juliacpowell1999** [scipion-em/scipion-pyworkflow#362]
Hello,

I am trying to run xmipp3 align-cl2d in scipion with particles imported from relion 4. I imported the particles as a run_it_data.star file from a previous class 2d job in relion 4. The import seemed to work just fine as the particles were visible and I was able to filter them using Spider filter-particles command in scipion. However, when I try to run alignment on filtered particles I get the following error:

XMIPP_ERROR 15:  Index out of bounds.
05001:   readSpider (1000001@Runs/001045_SpiderProtFilter/particles_filtered.stk): Image number 1000001 exceeds stack size 999999
05002:   File: core/rwSPIDER.cpp line: 204
05003:   XMIPP_ERROR 15:  Index out of bounds.
05004:   readSpider (1000007@Runs/001045_SpiderProtFilter/particles_filtered.stk): Image number 1000007 exceeds stack size 999999
05005:   File: core/rwSPIDER.cpp line: 204
05006:   XMIPP_ERROR 15:  Index out of bounds.
05007:   readSpider (1000003@Runs/001045_SpiderProtFilter/particles_filtered.stk): Image number 1000003 exceeds stack size 999999
05008:   File: core/rwSPIDER.cpp line: 204
05009:   XMIPP_ERROR 15:  Index out of bounds.
05010:   readSpider (1000005@Runs/001045_SpiderProtFilter/particles_filtered.stk): Image number 1000005 exceeds stack size 999999
05011:   File: core/rwSPIDER.cpp line: 204
05012:   XMIPP_ERROR 15:  Index out of bounds.
05013:   readSpider (1000004@Runs/001045_SpiderProtFilter/particles_filtered.stk): Image number 1000004 exceeds stack size 999999
05014:   File: core/rwSPIDER.cpp line: 204
05015:   XMIPP_ERROR 15:  Index out of bounds.
05016:   readSpider (1000002@Runs/001045_SpiderProtFilter/particles_filtered.stk): Image number 1000002 exceeds stack size 999999
05017:   File: core/rwSPIDER.cpp line: 204
05018:   XMIPP_ERROR 15:  Index out of bounds.
05019:   readSpider (1000006@Runs/001045_SpiderProtFilter/particles_filtered.stk): Image number 1000006 exceeds stack size 999999
05020:   File: core/rwSPIDER.cpp line: 204
05021:   XMIPP_ERROR 15:  Index out of bounds.
05022:   readSpider (1000000@Runs/001045_SpiderProtFilter/particles_filtered.stk): Image number 1000000 exceeds stack size 999999
05023:   File: core/rwSPIDER.cpp line: 204
05024:   --------------------------------------------------------------------------
05025:   Primary job  terminated normally, but 1 process returned
05026:   a non-zero exit code. Per user-direction, the job has been aborted.
05027:   --------------------------------------------------------------------------
05028:   --------------------------------------------------------------------------
05029:   mpirun detected that one or more processes exited with non-zero status, thus causing
05030:   the job to be terminated. The first process to do so was:
05031:   
05032:     Process name: [[30695,1],6]
05033:     Exit code:    15
05034:   --------------------------------------------------------------------------
05035:   Traceback (most recent call last):
05036:     File "/programs/x86_64-linux/scipion/3.0.0/.scipion3env/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 201, in run
05037:       self._run()
05038:     File "/programs/x86_64-linux/scipion/3.0.0/.scipion3env/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 252, in _run
05039:       resultFiles = self._runFunc()
05040:     File "/programs/x86_64-linux/scipion/3.0.0/.scipion3env/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 248, in _runFunc
05041:       return self._func(*self._args)
05042:     File "/programs/x86_64-linux/scipion/3.0.0/.scipion3env/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 1441, in runJob
05043:       self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
05044:     File "/programs/x86_64-linux/scipion/3.0.0/.scipion3env/lib/python3.8/site-packages/pyworkflow/protocol/executor.py", line 65, in runJob
05045:       process.runJob(log, programName, params,
05046:     File "/programs/x86_64-linux/scipion/3.0.0/.scipion3env/lib/python3.8/site-packages/pyworkflow/utils/process.py", line 52, in runJob
05047:       return runCommand(command, env, cwd)
05048:     File "/programs/x86_64-linux/scipion/3.0.0/.scipion3env/lib/python3.8/site-packages/pyworkflow/utils/process.py", line 67, in runCommand
05049:       check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr,
05050:     File "/programs/x86_64-linux/scipion/3.0.0/scipion_extlib/python-3.8.6-jhyh/lib/python3.8/subprocess.py", line 364, in check_call
05051:       raise CalledProcessError(retcode, cmd)
05052:   subprocess.CalledProcessError: Command ' mpirun -np 8  `which xmipp_mpi_classify_CL2D` -i Runs/001141_XmippProtCL2DAlign/extra/images.xmd --odir Runs/001141_XmippProtCL2DAlign/extra --nref 1 --iter 10 --maxShift 10 --nref0 1' returned non-zero exit status 15.
05053:   Protocol failed: Command ' mpirun -np 8  `which xmipp_mpi_classify_CL2D` -i Runs/001141_XmippProtCL2DAlign/extra/images.xmd --odir Runs/001141_XmippProtCL2DAlign/extra --nref 1 --iter 10 --maxShift 10 --nref0 1' returned non-zero exit status 15.

From a simple google search, I found a similar problem posted here https://sourceforge.net/p/scipion/mailman/message/37285586/ but I was a bit confused as to what the final solution was.

Any help would be appreciated!

Julia

**Comment by pconesa** [comment]
Hi Julia, thanks for reporting. it looks like xmipp image library (the one in charge of reading images) can't cope with stacks greater than 1M? or ate least those coming in an stk?

I'm assigning this to xmipp team.

**Comment by azazellochg** [comment]
Hi @juliacpowell1999 . Spider filter protocol script does not support more than 999999 images. Spider itself can handle stacks with up to 1.5mln images (if I read correctly https://github.com/spider-em/SPIDER/blob/master/src/CMLIMIT.INC). I suggest using some other plugin to filter particles.

**Comment by juliacpowell1999** [comment]
> Hi @juliacpowell1999 . Spider filter protocol script does not support more than 999999 images. Spider itself can handle stacks with up to 1.5mln images (if I read correctly https://github.com/spider-em/SPIDER/blob/master/src/CMLIMIT.INC). I suggest using some other plugin to filter particles.

@azazellochg Thank you for the reply! Just to clarify, I was able to filter all 1.3M particles with Spider, just not align them. Do you think I could split the particles into subsets for alignment, and then join them together for a class2D run using Spider? Or will Spider not support more than 1M particles for class 2D?

**Comment by azazellochg** [comment]
@juliacpowell1999 your Runs/001045_SpiderProtFilter/particles_filtered.stk has probably been overwritten and has only 999999 particles (you can check the header with e.g. eman2). You could split the data into two parts, yes. Though operating a huge binary stacks is not a very efficient idea. Spider has been deprecated few years ago, why not use relion or eman or cryosparc for 2D classification?
