### ISSUE TITLE
Scipion GUI frozen

### ISSUE THREAD

**Issue by juliacpowell1999** [scipion-em/scipion-pyworkflow#372]
Hello,

The Scipion GUI for one of my scipion projects is frozen. Scipion will load the project, but anytime I try to execute a new job the GUI freezes. It appears to be specific to this project, because I can run jobs for a different scipion project (located in a different directory) without issue.

For reference, the scipion version I have is v3.0.10 and was installed through sbgrid. I do not recall having two instances of the scipion open at the same time or doing anything else too terribly egregious to cause the GUI to freeze. 

Do you have any suggestions on how to proceed? Does scipion have a lock file (similar to a relion lock file), which prevents two instances from being open at the same time, that I need to delete? 

Thank you!

Julia

**Comment by pconesa** [comment]
Hi Julia!... there are a couple of things you can do.

Ask sbgrid maintainers to update scipion, we have just released new code and, although I do not remember fixing this type of error it is good to be updated.

Second, let's try to see if we can get more information:

Add to your config file (scipion3 config --show) will show you the config file, this line:

SCIPION_LOG_LEVEL = DEBUG

Try to reproduce it again and see if there is anything in the terminal that looks suspicious. Send it here.

Cheers, Pablo.
