### ISSUE TITLE
NumericRangeParam and NumericListParam

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-pyworkflow#375]
Both should return a list by default, not a string.

**Comment by azazellochg** [comment]
Nobody was interested.

**Comment by pconesa** [comment]
nope, I'm currenlty on it.

**Comment by azazellochg** [comment]
pwutils already has two methods to return a list

**Comment by pconesa** [comment]
I know 1: getListFromValues plus companions (Bool, Float, ...)

**Comment by pconesa** [comment]
getListFromRangeString ?

**Comment by azazellochg** [comment]
yes
