### ISSUE TITLE
Every time a new protocol is created, the box is on the top

### ISSUE THREAD

**Issue by delarosatrevin** [scipion-em/scipion-pyworkflow#381]
<img width="50%" alt="Screen Shot 2022-09-30 at 4 10 07 PM" src="https://user-images.githubusercontent.com/8441688/193601883-4f469491-97d1-4122-b66d-eb8371f0841b.png">
<img width="50%" alt="Screen Shot 2022-09-30 at 4 21 31 PM" src="https://user-images.githubusercontent.com/8441688/193601891-06303aa6-65d3-42a1-ab75-c06cc62919dc.png">

**Comment by azazellochg** [comment]
I confirm that

**Comment by pconesa** [comment]
I think it only happens when it's saved for some reason. If it's executed right away it goes fine. We'll fix it.

**Comment by delarosatrevin** [comment]
I think in my case I have executed the jobs directly...but might be a slow filesystem that I see the jobs in saved/launched/running states.

**Comment by pconesa** [comment]
Fixed and released yesterday
