### ISSUE TITLE
Allow interation with scipion when emanDataViewer dialog is open

### ISSUE THREAD

**Issue by fede-pe** [scipion-em/scipion-pyworkflow#483]
When this dialog is open
![image](https://github.com/scipion-em/scipion-em-emantomo/assets/49978869/7401bbfe-425a-4469-a0eb-a580491d4187)

it is not possible to interact with scipion, being this inconvenient for processing while checking the peaked coordinates / open two different sets at the same time.

**Comment by azazellochg** [comment]
I think this is fixed?
