### ISSUE TITLE
projects error

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-pyworkflow#484]
"We have recently had to upgrade to a newer Scipion version (v3.3.0) in SBGRID.  FYI, associated packages are on these versions:

scipion-app                3.3.0
scipion-em                 3.3.1
scipion-pyworkflow         3.3.1

The problem is that we create and schedule projects using templates, ie:

$ scipion3 python -m pyworkflow.project.scripts.create PROJECT TEMPLATE.json

$ scipion3 python -m pyworkflow.project.scripts.schedule PROJECT

Previously this worked fine, but the created projects are now giving an AttributeError with the newer version of Scipion when they are run, reset or loaded":

 

```
  File "/home/me/.local/lib/python3.8/site-packages/pyworkflow/project/project.py", line 513, in _fixProtParamsConfiguration

    pointer.set(self.getRunsGraph().getNode(str(pointer.get().getObjParentId())).run)

AttributeError: 'NoneType' object has no attribute 'getObjParentId'
```

**Comment by pconesa** [comment]
CAn we have access to the template?
