### ISSUE TITLE
Xmipp and Scipion installation problem on Debian 12 machine 

### ISSUE THREAD

**Issue by TomCrey** [scipion-em/scipion-pyworkflow#515]
Dear all, 

We're trying to install Xmipp in order to use Scipion3, but we're having a few problems with the installation (cf terminal output below). We're trying to install it on a machine running Debian 12; do you know if it's possible to install Xmipp on this type of machine?  

Thank you for your help, 

Tom
_______________________________
`Unable to install Xmipp.
Some error found compiling 'basic_mem_manager.o' program.. 
 You can skip this program by including 'CUDA=False' in the config file. 
 For more information about the error check compileLOG.txt file if exist.
 You can visit our guide of installation https://github.com/I2PC/xmipp,
 visit the wiki page with some details https://github.com/I2PC/xmipp/wiki 
 and you can contact us xmipp@cnb.csic.es or Discord/Scipion/xmipp
To report the details of the error please share the reportInstallation.tar.gz file `

**Comment by pconesa** [comment]
Let's see if anyone from xmipp team have a clue.

@oierlauzi?

Have you tried to follow what the message says:

"You can skip this program by including 'CUDA=False' in the config file"

If it is not clear, just do:

1.- scipion3 config --show   (should pop up a text file with variables and values)
2.- add/edit a line :  CUDA=False
3.- install xmipp again:  scipion3 install xmippSrc

**Comment by oierlauzi** [comment]
Hello, 
Xmipp should work on Debian. I personally use it. As Pablo says, maybe you could try compiling without CUDA at least you are likely to get a working Scipion installation. In any case, please, could you send me your /path/to/scipion/software/em/xmippSrc-?????/compileLOG.txt

**Comment by TomCrey** [comment]
Hi @oierlauzi, 
Yes, of course, here it is: 

Compilation Date: 2024-04-23 16:31:45.402295


###########################
Compiling cuFFTAdvisor--------
mkdir -p build/
nvcc --cudart static -shared -link -Wno-deprecated-gpu-targets -o build/libcuFFTAdvisor.so obj/advisor.o obj/benchmarker.o obj/benchmarkResult.o obj/cudaAsserts.o obj/generalTransform.o obj/inputParser.o obj/main.o obj/sizeOptimizer.o obj/transform.o obj/transformGenerator.o obj/validator.o
mkdir -p build/
nvcc -o build/cuFFTAdvisor obj/advisor.o obj/benchmarker.o obj/benchmarkResult.o obj/cudaAsserts.o obj/generalTransform.o obj/inputParser.o obj/main.o obj/sizeOptimizer.o obj/transform.o obj/transformGenerator.o obj/validator.o -lcufft -Wno-deprecated-gpu-targets

###########################
Compiling googletest--------
-- Configuring done
-- Generating done
-- Build files have been written to: /storage/home/tcrey/scipion3/software/em/xmippSrc-v3.23.11.0/src/googletest/build
[100%] Built target gtest
[ 50%] Built target gtest
[100%] Built target gtest_main

###########################
Compiling libsvm--------
if [ "Linux" = "Darwin" ]; then \
	SHARED_LIB_FLAG="-dynamiclib -Wl,-install_name,libsvm.so"; \
else \
	SHARED_LIB_FLAG="-shared -Wl,-soname,libsvm.so"; \
fi; \
g++ ${SHARED_LIB_FLAG} svm.o -o libsvm.so

###########################
Compiling libcifpp--------
Not trying to recreate symop_table_data.hpp since CCP4 is not defined
-- Testing for known regex bug, since you're using GNU libstdc++
-- You are probably trying to compile using the g++ standard library which contains a crashing std::regex implementation. Will use boost::regex instead
-- Configuring done
-- Generating done
-- Build files have been written to: /storage/home/tcrey/scipion3/software/em/xmippSrc-v3.23.11.0/src/libcifpp/build
[  4%] Building CXX object CMakeFiles/cifpp.dir/src/utilities.cpp.o
[  9%] Linking CXX shared library libcifpp.so
[100%] Built target cifpp
-- Install configuration: "Release"
-- Installing: /storage/home/tcrey/scipion3/software/em/xmippSrc-v3.23.11.0/src/libcifpp/lib/libcifpp.so.5.0.9
-- Up-to-date: /storage/home/tcrey/scipion3/software/em/xmippSrc-v3.23.11.0/src/libcifpp/lib/libcifpp.so.5
-- Up-to-date: /storage/home/tcrey/scipion3/software/em/xmippSrc-v3.23.11.0/src/libcifpp/lib/libcifpp.so
-- Up-to-date: /storage/home/tcrey/scipion3/software/em/xmippSrc-v3.23.11.0/src/libcifpp/lib/cmake/cifpp/cifppTargets.cmake
-- Up-to-date: /storage/home/tcrey/scipion3/software/em/xmippSrc-v3.23.11.0/src/libcifpp/lib/cmake/cifpp/cifppTargets-release.cmake
-- Up-to-date: /storage/home/tcrey/scipion3/software/em/xmippSrc-v3.23.11.0/src/libcifpp/include/cif++/exports.hpp
-- Up-to-date: /storage/home/tcrey/scipion3/software/em/xmippSrc-v3.23.11.0/src/libcifpp/share/libcifpp/mmcif_ddl.dic
-- Up-to-date: /storage/home/tcrey/scipion3/software/em/xmippSrc-v3.23.11.0/src/libcifpp/share/libcifpp/mmcif_pdbx.dic
-- Up-to-date: /storage/home/tcrey/scipion3/software/em/xmippSrc-v3.23.11.0/src/libcifpp/share/libcifpp/mmcif_ma.dic
-- Up-to-date: /storage/home/tcrey/scipion3/software/em/xmippSrc-v3.23.11.0/src/libcifpp/lib/cmake/cifpp/cifppConfig.cmake
-- Up-to-date: /storage/home/tcrey/scipion3/software/em/xmippSrc-v3.23.11.0/src/libcifpp/lib/cmake/cifpp/cifppConfigVersion.cmake
-- Up-to-date: /storage/home/tcrey/scipion3/software/em/xmippSrc-v3.23.11.0/src/libcifpp/lib/pkgconfig/libcifpp.pc

###########################
Compiling XmippCore--------
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: `lib/libXmippCore.so' is up to date.
scons: `lib/xmippCore.so' is up to date.
scons: done building targets.


###########################
Compiling Xmipp------------
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
scons: `lib/libXmipp.so' is up to date.
scons: `lib/_swig_frm.so' is up to date.
/usr/local/cuda/bin/nvcc -o libraries/reconstruction_cuda/basic_mem_manager.o -c --x cu -D_FORCE_INLINES -Xcompiler -fPIC -ccbin -std=c++14 --expt-extended-lambda -gencode=arch=compute_60,code=compute_60 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_86,code=compute_86 -I../ -I/home/tcrey/miniconda3/envs/scipion3/include -Iexternal -Ilibraries -I/storage/home/tcrey/scipion3/software/em/xmippSrc-v3.23.11.0/src/xmippCore -I/storage/home/tcrey/scipion3/software/em/xmippSrc-v3.23.11.0/src/libcifpp/include libraries/reconstruction_cuda/basic_mem_manager.cpp
-std=c++14: No such file or directory
Building compilation database /storage/home/tcrey/scipion3/software/em/xmippSrc-v3.23.11.0/compile_commands.json
nvcc fatal   : Failed to preprocess host compiler properties.
/usr/local/cuda/bin/nvcc -o libraries/reconstruction_cuda/cuda_all.o -c --x cu -D_FORCE_INLINES -Xcompiler -fPIC -ccbin -std=c++14 --expt-extended-lambda -gencode=arch=compute_60,code=compute_60 -gencode=arch=compute_61,code=compute_61 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_86,code=compute_86 -I../ -I/home/tcrey/miniconda3/envs/scipion3/include -Iexternal -Ilibraries -I/storage/home/tcrey/scipion3/software/em/xmippSrc-v3.23.11.0/src/xmippCore -I/storage/home/tcrey/scipion3/software/em/xmippSrc-v3.23.11.0/src/libcifpp/include libraries/reconstruction_cuda/cuda_all.cpp
scons: *** [libraries/reconstruction_cuda/basic_mem_manager.o] Error 1
-std=c++14: No such file or directory
nvcc fatal   : Failed to preprocess host compiler properties.
scons: *** [libraries/reconstruction_cuda/cuda_all.o] Error 1
scons: building terminated because of errors.

**Comment by oierlauzi** [comment]
Hello again. What nvidia driver do you have? and what cuda-toolkit? A quick look of the error (nvcc fatal : Failed to preprocess host compiler properties.) does not shed any light on the issue.

**Comment by azazellochg** [comment]
Does /usr/local/cuda/bin/nvcc exist?

**Comment by TomCrey** [comment]
> Hello again. What nvidia driver do you have? and what cuda-toolkit? A quick look of the error (nvcc fatal : Failed to preprocess host compiler properties.) does not shed any light on the issue.

Hello @oierlauzi, 

Nvidia driver version : 535.154.05
Cuda-toolkit : V11.8.89

Thanks for your help !

**Comment by oierlauzi** [comment]
Thanks! That looks okay. Please, also attach /path/to/scipion/software/em/xmippSrc-?????/xmipp.conf

**Comment by oierlauzi** [comment]
I think I have a clue. You may have g++-12 installed, but CUDA 11.8 only supports up to g++-11. 2. If the config file confirms this hypothesis, the solution will be rather simple.

**Comment by TomCrey** [comment]
We have solved our problem, it was a bad version of CUDA (11.8) which prevented the correct installation of Xmipp; with the CUDA 12.2 version everything seems to work normally for the moment. 

Thank you all for your help! 

Tom
