### ISSUE TITLE
can not access to scipion.i2pc.es

### ISSUE THREAD

**Issue by menmt0930** [scipion-em/scipion-pyworkflow#522]
scipion.i2pc.es site is marked as highly risky and I can't access from any browser.
Also, I can't load any plugin info at all from scipion3 GUI.
How can I solve this issue?

**Comment by pconesa** [comment]
scipion does not use scipion.i2pc.es but scipion.cnb.csic.es. 

Does still happen for https://scipion.i2pc.es?


In any case the installation of a plugin can be bypassed with:

scipion3 pip install scipion-em-PLUGINNAME


You might be able to see the list here: https://pypi.org/search/?q=scipion-em

But then, you can run scipion3 installb 

To list and install the binaries. Some of them are downloaded from scipion.cnb.csic.es, So you may be unable to install them.

You can always install the software Scipion integrates manually (from their respective sites) and then link the software as described here:

https://scipion-em.github.io/docs/release-3.0.0/docs/scipion-modes/linking-existing-software.html

**Comment by azazellochg** [comment]
scipion3 installp -h
Scipion v3.4.0 - Eugenius
WARNING: Can't get Scipion's plugin list, the plugin repository is not available
