### ISSUE TITLE
pyworkflow 3.7.1 update dependency error message

### ISSUE THREAD

**Issue by wlugmayr** [scipion-em/scipion-pyworkflow#545]
hi,

after the upgrade the user interface comes up without warning but during install the following error message appeared:

Installing collected packages: requests, pillow, numpy, configparser, matplotlib, scipion-pyworkflow
  Attempting uninstall: requests
    Found existing installation: requests 2.28.1
    Uninstalling requests-2.28.1:
      Successfully uninstalled requests-2.28.1
  Attempting uninstall: pillow
    Found existing installation: Pillow 9.2.0
    Uninstalling Pillow-9.2.0:
      Successfully uninstalled Pillow-9.2.0
  Attempting uninstall: numpy
    Found existing installation: numpy 1.23.0
    Uninstalling numpy-1.23.0:
      Successfully uninstalled numpy-1.23.0
  Attempting uninstall: configparser
    Found existing installation: configparser 5.2.0
    Uninstalling configparser-5.2.0:
      Successfully uninstalled configparser-5.2.0
  Attempting uninstall: matplotlib
    Found existing installation: matplotlib 3.5.2
    Uninstalling matplotlib-3.5.2:
      Successfully uninstalled matplotlib-3.5.2
  Attempting uninstall: scipion-pyworkflow
    Found existing installation: scipion-pyworkflow 3.6.0
    Uninstalling scipion-pyworkflow-3.6.0:
      Successfully uninstalled scipion-pyworkflow-3.6.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
scipion-em 3.7.1 requires matplotlib<=3.5.2, but you have matplotlib 3.7.3 which is incompatible.
scipion-em 3.7.1 requires Pillow<=9.2.0, but you have pillow 10.1.0 which is incompatible.
Successfully installed configparser-6.0.0 matplotlib-3.7.3 numpy-1.24.4 pillow-10.1.0 requests-2.31.0 scipion-pyworkflow-3.7.0
scipion-pyworkflow was correctly updated.

$ scipion3 update
Scipion v3.6.0 - Eugenius
The package scipion-pyworkflow is up to date.  Your version is 3.7.0
The package scipion-em is up to date.  Your version is 3.7.1
The package scipion-app is up to date.  Your version is 3.6.0
Scipion is up to date.

**Comment by azazellochg** [comment]
Could you post `scipion3 pip list` output please?

**Comment by azazellochg** [comment]
My guess you have a plugin that conflicts with the new core. Most likely xmipp-metadata or scipion-em-flexutils ..

**Comment by wlugmayr** [comment]
here are my installed plugins:
scipion-em-aretomo             3.9.3      [X]
scipion-em-chimera             3.4.0      [X]
scipion-em-cistem              3.9.2      [X]
scipion-em-cryocare            4.1.0      [X]
scipion-em-dynamo              3.1.21     [X]
scipion-em-eman2               3.6.1      [X]
scipion-em-emantomo            3.3.1      [X]
scipion-em-gctf                3.1.3      [X]
scipion-em-imod                3.5.1      [X]
scipion-em-isonet              3.0.1      [X]
scipion-em-motioncorr          3.16.3     [X]
scipion-em-novactf             3.2        [X]
scipion-em-relion              5.0.0b8    [X]
scipion-em-reliontomo          3.4.0      [X]
scipion-em-sphire              3.2.2      [X]
scipion-em-susantomo           3.0b4      [X]
scipion-em-tomo                3.7.2      [X]
scipion-em-tomo3d              3.1.2      [X]
scipion-em-tomosegmemtv        3.1.2      [X]
scipion-em-tomotwin            3.5        [X]
scipion-em-tomoviz             3.1.4      [X]
scipion-em-topaz               3.0.2      [X]
scipion-em-warp                3.2.4      [X]
scipion-em-xmipp               24.6.0.0   [X]
scipion-em-xmipptomo           3.24.6.1   [X]

**Comment by wlugmayr** [comment]
Package                       Version
----------------------------- ----------
alabaster                     0.7.12
Babel                         2.9.1
cached-property               1.5.2
chardet                       4.0.0
click                         8.0.3
ClusterShell                  1.9.2
Cython                        0.29.22
dasbus                        1.4
dbus-python                   1.2.18
decorator                     4.4.2
distro                        1.5.0
docutils                      0.16
file-magic                    0.4.0
future                        0.18.3
gpg                           1.15.1
h5py                          3.7.0
idna                          2.10
imagesize                     1.2.0
iniparse                      0.4
Jinja2                        2.11.3
libcomps                      0.1.18
lxml                          4.6.5
Mako                          1.1.4.dev0
Markdown                      3.3.4
MarkupSafe                    1.1.1
mercurial                     6.1.4
meson                         0.63.3
nagiosplugin                  1.3.3
nftables                      0.1
numexpr                       2.8.4
numpy                         1.20.1
packaging                     20.9
passlib                       1.7.4
perf                          0.1
pexpect                       4.8.0
pip                           21.2.3
Pmw                           2.1.1
podman-compose                1.0.6
pssh                          2.3.4
psutil                        5.8.0
psycopg2                      2.8.6
ptyprocess                    0.6.0
pycairo                       1.20.1
pygame                        2.3.0
Pygments                      2.7.4
PyGObject                     3.40.1
pyinotify                     0.9.6
pyparsing                     2.4.7
pyslurm                       23.11.0
PySocks                       1.7.1
python-dateutil               2.8.1
python-dotenv                 0.19.2
python-linux-procfs           0.7.3
pytz                          2021.1
pyudev                        0.22.0
PyYAML                        5.4.1
requests                      2.25.1
rpm                           4.16.1.3
scipy                         1.6.2
SCons                         4.5.2
selinux                       3.6
sepolicy                      3.6
setools                       4.4.4
setroubleshoot                3.3.32
setuptools                    53.0.0
six                           1.15.0
snowballstemmer               1.9.0
sos                           4.7.1
Sphinx                        3.4.3
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        1.0.3
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.4
subscription-manager          1.29.40
systemd-python                234
tables                        3.7.0
urllib3                       1.26.5
wheel                         0.36.2

**Comment by azazellochg** [comment]
For some reason, you have two outdated packages, tifffile and biopython. Both should get updated by new scipion-em. Could you update sequentially:
```
conda activate scipion3
pip install -U scipion-pyworkflow
pip install -U scipion-em
pip install -U scipion-app
```
and see if this gives any errors.

**Comment by wlugmayr** [comment]
the commands worked. here are the relevant log entries:

Installing collected packages: tifffile, biopython, scipion-em
  Attempting uninstall: tifffile
    Found existing installation: tifffile 2021.11.2
    Uninstalling tifffile-2021.11.2:
      Successfully uninstalled tifffile-2021.11.2
  Attempting uninstall: biopython
    Found existing installation: biopython 1.79
    Uninstalling biopython-1.79:
      Successfully uninstalled biopython-1.79
  Attempting uninstall: scipion-em
    Found existing installation: scipion-em 3.7.1
    Uninstalling scipion-em-3.7.1:
      Successfully uninstalled scipion-em-3.7.1
Successfully installed biopython-1.81 scipion-em-3.8.0 tifffile-2023.7.10

**Comment by azazellochg** [comment]
Alright, then you should be good!
