### ISSUE TITLE
queue submission not working

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-pyworkflow#70]
Why SCIPION_HOSTS = ~/soft/scipion3/scipion-app/scipion/templates/hosts.template and not %(SCIPION_HOME)s/config/hosts.conf ?

**Comment by azazellochg** [comment]
Also, what happened here???
![Screenshot_20200326_163258](https://user-images.githubusercontent.com/6952870/77671556-b667b100-6f7f-11ea-9a98-88edd6363763.png)

**Comment by delarosatrevin** [comment]
My wild guess is that the config file parsing is not working properly.

**Comment by pconesa** [comment]
thank, for the "Why SCIPION_HOSTS = ~/soft/scipion3/scipion-app/scipion/templates/hosts.template and not %(SCIPION_HOME)s/config/hosts.conf ?"

I think because you are using ~, and is not being "extended".

**Comment by azazellochg** [comment]
I don't want to use template, i want to use my config.


Best regards,
Grigory

--------------------------------------------------------------------------------
Grigory Sharov, Ph.D.

MRC Laboratory of Molecular Biology,
Francis Crick Avenue,
Cambridge Biomedical Campus,
Cambridge CB2 0QH, UK.
tel. +44 (0) 1223 267228 <+44%201223%20267228>
e-mail: gsharov@mrc-lmb.cam.ac.uk

**Comment by azazellochg** [comment]
Also, %_(JOB_ID)s was silently changed to %%(JOB_ID)s format

Best regards,
Grigory

--------------------------------------------------------------------------------
Grigory Sharov, Ph.D.

MRC Laboratory of Molecular Biology,
Francis Crick Avenue,
Cambridge Biomedical Campus,
Cambridge CB2 0QH, UK.
tel. +44 (0) 1223 267228
e-mail: gsharov@mrc-lmb.cam.ac.uk


On Fri, Mar 27, 2020 at 2:51 PM Grigory Sharov <sharov.grigory@gmail.com>
wrote:
>
> I don't want to use template, i want to use my config.
>
>
> Best regards,
> Grigory
>
>
--------------------------------------------------------------------------------
> Grigory Sharov, Ph.D.
>
> MRC Laboratory of Molecular Biology,
> Francis Crick Avenue,
> Cambridge Biomedical Campus,
> Cambridge CB2 0QH, UK.
> tel. +44 (0) 1223 267228
> e-mail: gsharov@mrc-lmb.cam.ac.uk
>
>
> On Fri, Mar 27, 2020 at 2:37 PM Pablo Conesa <notifications@github.com>
wrote:
>>
>> thank, for the "Why SCIPION_HOSTS =
~/soft/scipion3/scipion-app/scipion/templates/hosts.template and not
%(SCIPION_HOME)s/config/hosts.conf ?"

**Comment by azazellochg** [comment]
Any examples of working QUEUES dict?


Best regards,
Grigory

--------------------------------------------------------------------------------
Grigory Sharov, Ph.D.

MRC Laboratory of Molecular Biology,
Francis Crick Avenue,
Cambridge Biomedical Campus,
Cambridge CB2 0QH, UK.
tel. +44 (0) 1223 267228 <+44%201223%20267228>
e-mail: gsharov@mrc-lmb.cam.ac.uk

**Comment by pconesa** [comment]
probably all is failing in terms of queues + python3

**Comment by pconesa** [comment]
SCIPION_HOSTS has a default value, you can define it in scipion.conf and point to the one you want

**Comment by azazellochg** [comment]
I'm getting tired of this... it's not working and it was working in scipion 2!
hosts.conf:
```
[localhost]
CANCEL_COMMAND = qdel %%(JOB_ID)s
CHECK_COMMAND = qstat %%(JOB_ID)s
JOB_DONE_REGEX = ""
MANDATORY = 0
NAME = SGE
PARALLEL_COMMAND = mpiexec -mca orte_forward_job_control 1 -n %%(JOB_NODES)d %%(COMMAND)s
SUBMIT_PREFIX = scipion
SUBMIT_COMMAND = unset module; qsub %%(JOB_SCRIPT)s
SUBMIT_TEMPLATE = #!/bin/sh
        #$ -V
        #$ -N scipion%%(JOB_NAME)s
        #$ -pe %%(JOB_PE_TYPE)s %%(JOB_NODES2)d
        #$ -l dedicated=%%(JOB_THREADS)d
        #$ -e %%(JOB_SCRIPT)s.err
        #$ -o %%(JOB_SCRIPT)s.out
        #$ -cwd
        #$ -S /bin/bash
        %%(JOB_EXTRA_PARAMS)s
        %%(JOB_COMMAND)s
QUEUES = {
        "CPU single node": [["JOB_PE_TYPE", "smp", "SGE PE type", "Select SGE PE type: openmpi or smp"], ["JOB_EXTRA_PARAMS", "", "Extra params", "Provide extra params for SGE"]],
        "CPU 24 cores": [["JOB_PE_TYPE", "openmpi", "SGE PE type", "Select SGE PE type: openmpi or smp"], ["JOB_EXTRA_PARAMS", "#$ -l dedicated=24 -A Relion", "Extra params", "Use odd number of MPIs"]],
        "GPU 32 cores": [["JOB_PE_TYPE", "openmpi", "SGE PE type", "Select SGE PE type: openmpi"], ["JOB_EXTRA_PARAMS", "#$ -pe openmpi 1 -l dedicated=32 -l gpu=4 -A Relion", "Extra params", "Use odd number of MPIs"]],
        "GPU 64 cores": [["JOB_PE_TYPE", "openmpi", "SGE PE type", "Select SGE PE type: openmpi"], ["JOB_EXTRA_PARAMS", "#$ -pe openmpi 1 -l dedicated=64 -l gpu=4 -l gpu_cc=7.5 -A Relion", "Extra params", "Use odd number of MPIs"]]
        }
```
scipion6883.job:
```
#!/bin/sh
#$ -pe openmpi 1 -l dedicated=32 -l gpu=4 -A Relion
/lmb/home/gsharov/soft/scipion3/scipion-pyworkflow/pyworkflow/apps/pw_protocol_run.py "/lmb/home/gsharov/cephfs/ScipionUserData/projects/relion31_tutorial_scipion" "Runs/006883_ProtRelionClassify2D/logs/run.db" 6883
```

Where did the other variables go?

**Comment by fonsecareyna82** [comment]
With the same host.conf that error does not appear to me. 
![Captura de pantalla de 2020-05-06 20-19-21](https://user-images.githubusercontent.com/34970661/81213659-000fd680-8fd7-11ea-8fee-ed18e4707f9a.png)

**Comment by azazellochg** [comment]
Yes, the job submits to the queue, but did you check what it submits?

Best regards,
Grigory

--------------------------------------------------------------------------------
Grigory Sharov, Ph.D.

MRC Laboratory of Molecular Biology,
Francis Crick Avenue,
Cambridge Biomedical Campus,
Cambridge CB2 0QH, UK.
tel. +44 (0) 1223 267228 <+44%201223%20267228>
e-mail: gsharov@mrc-lmb.cam.ac.uk

**Comment by pconesa** [comment]
Hi @azazellochg , I'm sorry that you are getting tired of this error. We are overloaded with tasks and I must admit that, although @fonsecareyna82 took some time to fix this it might not have fix all but partially. 

All we can do is keep fixing things. Theoretically, the same host.conf file should be compatible with scipion3. 

We do not have a permanent queue system ready to test this things. Probably mocking some code might help.

**Comment by pconesa** [comment]
I'm looking at this...it seems the ConfigParser is ignoring those lines.

**Comment by pconesa** [comment]
THis is what we get after the read: --> '#!/bin/sh
%(JOB_EXTRA_PARAMS)s
%(JOB_COMMAND)s'

**Comment by azazellochg** [comment]
yes, this is what I get
Best regards,
Grigory

--------------------------------------------------------------------------------
Grigory Sharov, Ph.D.

MRC Laboratory of Molecular Biology,
Francis Crick Avenue,
Cambridge Biomedical Campus,
Cambridge CB2 0QH, UK.
tel. +44 (0) 1223 267228 <+44%201223%20267228>
e-mail: gsharov@mrc-lmb.cam.ac.uk

**Comment by pconesa** [comment]
Hi, @azazellochg do you think this line is wrong:

#$ -pe %%(JOB_PE_TYPE)s %%(JOB_NODES2)d

JOB_NODES2 dos not exists!

**Comment by azazellochg** [comment]
Hi Pablo,

it does exist in my modified version of pyworkflow/protocol/protocol.py.
You can remove it for your test.

Best regards,
Grigory

--------------------------------------------------------------------------------
Grigory Sharov, Ph.D.

MRC Laboratory of Molecular Biology,
Francis Crick Avenue,
Cambridge Biomedical Campus,
Cambridge CB2 0QH, UK.
tel. +44 (0) 1223 267228 <+44%201223%20267228>
e-mail: gsharov@mrc-lmb.cam.ac.uk

**Comment by pconesa** [comment]
Thanks. Does this look correct

#!/bin/sh
##$ -V
##$ -N scipion2780
##$ -pe openmpi 1
##$ -l dedicated=1
##$ -e Runs/002780_XmippProtCropResizeParticles/logs/scipion2780.job.err
##$ -o Runs/002780_XmippProtCropResizeParticles/logs/scipion2780.job.out
##$ -cwd
#$ -S /bin/bash
#$ -pe openmpi 1 -l dedicated=32 -l gpu=4 -A Relion
/home/pablo/desarrollo/scipion-pyworkflow/pyworkflow/apps/pw_protocol_run.py "/home/pablo/ScipionUserData/projects/EMPIAR10200" "Runs/002780_XmippProtCropResizeParticles/logs/run.db" 2780

**Comment by azazellochg** [comment]
No, number of hash signs should be 1  not 2

**Comment by pconesa** [comment]
So, ## is meant to escape the hash?

**Comment by azazellochg** [comment]
qsub requires #$ as first two chars of the string

Best regards,
Grigory

--------------------------------------------------------------------------------
Grigory Sharov, Ph.D.

MRC Laboratory of Molecular Biology,
Francis Crick Avenue,
Cambridge Biomedical Campus,
Cambridge CB2 0QH, UK.
tel. +44 (0) 1223 267228 <+44%201223%20267228>
e-mail: gsharov@mrc-lmb.cam.ac.uk

**Comment by pconesa** [comment]
Ok, if I'm getting it right, from https://docs.python.org/3/library/configparser.html

> Changed in version 3.2: In previous versions of configparser behaviour matched comment_prefixes=('#',';') and inline_comment_prefixes=(';',).
> 
> Please note that config parsers don’t support escaping of comment prefixes so using inline_comment_prefixes may prevent users from specifying option values with characters used as comment prefixes. When in doubt, avoid setting inline_comment_prefixes. In any circumstances, the only way of storing comment prefix characters at the beginning of a line in multiline values is to interpolate the prefix, for example:

I've looked at the code too, and I couldn't find a way to bypass the read behaviour, which is to Skip any line that Starts with a "comment" char.

By deafult in Python3, comment chars are: #, ;
We can ignore the # as a comment char, but then we will get the double ##.

At this point I do not see a way to keep the compatibility with existing config files and using the ConfigParser.

@delarosatrevin , any ideas? 

If we "break" compatibility, probably the easiest way to adapt existing configs would be to replace lines starting with ## by #.....this...we can do in code? Should we?.

**Comment by azazellochg** [comment]
Compatibility is already broken since someone replaced %_ by %%.

**Comment by pconesa** [comment]
I wasn't realizing that. I've found a easy way to preserve ## compatibility.
I'll look at %_ / %% case too.

**Comment by azazellochg** [comment]
Thank you for looking into this, Pablo. Much appreciated!

Best regards,
Grigory

--------------------------------------------------------------------------------
Grigory Sharov, Ph.D.

MRC Laboratory of Molecular Biology,
Francis Crick Avenue,
Cambridge Biomedical Campus,
Cambridge CB2 0QH, UK.
tel. +44 (0) 1223 267228 <+44%201223%20267228>
e-mail: gsharov@mrc-lmb.cam.ac.uk

**Comment by pconesa** [comment]
Thanks to you!

Anyone aware of host files containing environment variables?

There is a chance to restore the "%_" (once more a python3 missing feature), but we will need to avoid interpolation....this will cancel any interpolation that might have been done by the parser itself and not by us.

**Comment by pconesa** [comment]
I think I got it right now with the old format. @azazellochg if this end up being the final solution, you'l need to undo your host.conf changes to the old format. 

Config with %_ and ## at the beginning of lines.
````
[localhost]
CANCEL_COMMAND = qdel %_(JOB_ID)s
CHECK_COMMAND = qstat %_(JOB_ID)s
JOB_DONE_REGEX = ""
MANDATORY = 0
NAME = SGE
PARALLEL_COMMAND = mpiexec -mca orte_forward_job_control 1 -n %_(JOB_NODES)d %_(COMMAND)s
SUBMIT_PREFIX = scipion
SUBMIT_COMMAND = unset module; qsub %_(JOB_SCRIPT)s
SUBMIT_TEMPLATE = #!/bin/sh
        ##$ -V
        ##$ -N scipion%_(JOB_NAME)s
        ##$ -pe %_(JOB_PE_TYPE)s %_(JOB_NODES)d
        ##$ -l dedicated=%_(JOB_THREADS)d
        ##$ -e %_(JOB_SCRIPT)s.err
        ##$ -o %_(JOB_SCRIPT)s.out
        ##$ -cwd
        #$ -S /bin/bash
        %_(JOB_EXTRA_PARAMS)s
        %_(JOB_COMMAND)s
QUEUES = {
        "CPU single node": [["JOB_PE_TYPE", "smp", "SGE PE type", "Select SGE PE type: openmpi or smp"], ["JOB_EXTRA_PARAMS", "", "Extra params", "Provide extra params for SGE"]],
        "CPU 24 cores": [["JOB_PE_TYPE", "openmpi", "SGE PE type", "Select SGE PE type: openmpi or smp"], ["JOB_EXTRA_PARAMS", "#$ -l dedicated=24 -A Relion", "Extra params", "Use odd number of MPIs"]],
        "GPU 32 cores": [["JOB_PE_TYPE", "openmpi", "SGE PE type", "Select SGE PE type: openmpi"], ["JOB_EXTRA_PARAMS", "#$ -pe openmpi 1 -l dedicated=32 -l gpu=4 -A Relion", "Extra params", "Use odd number of MPIs"]],
        "GPU 64 cores": [["JOB_PE_TYPE", "openmpi", "SGE PE type", "Select SGE PE type: openmpi"], ["JOB_EXTRA_PARAMS", "#$ -pe openmpi 1 -l dedicated=64 -l gpu=4 -l gpu_cc=7.5 -A Relion", "Extra params", "Use odd number of MPIs"]]
        }
````




````
#!/bin/sh`
#$ -V
#$ -N scipion2780
#$ -pe openmpi 1
#$ -l dedicated=1
#$ -e Runs/002780_XmippProtCropResizeParticles/logs/scipion2780.job.err
#$ -o Runs/002780_XmippProtCropResizeParticles/logs/scipion2780.job.out
#$ -cwd
#$ -S /bin/bash
#$ -pe openmpi 1 -l dedicated=32 -l gpu=4 -A Relion
/extra/pablo/desarrollo/scipion-pyworkflow/pyworkflow/apps/pw_protocol_run.py "/home/pablo/ScipionUserData/projects/EMPIAR10200" "Runs/002780_XmippProtCropResizeParticles/logs/run.db" 2780
````
