### ISSUE TITLE
JSON serialization of mics fails

### ISSUE THREAD

**Issue by pconesa** [scipion-em/scipion-pyworkflow#76]
I was trying to make a consensus and got this error:

00013:   Traceback (most recent call last):
00014:     File "/home/pablo/desarrollo/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 188, in run
00015:       self._run()
00016:     File "/home/pablo/desarrollo/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 1317, in _run
00017:       self._runSteps(startIndex)
00018:     File "/home/pablo/desarrollo/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 1189, in _runSteps
00019:       self._stepsCheckSecs)
00020:     File "/home/pablo/desarrollo/scipion-pyworkflow/pyworkflow/protocol/executor.py", line 132, in runSteps
00021:       stepsCheckCallback()
00022:     File "/home/pablo/desarrollo/xmippBundleP3/src/scipion-em-xmipp/xmipp3/protocols/protocol_particle_pick_consensus.py", line 138, in _stepsCheck
00023:       self._checkNewInput()
00024:     File "/home/pablo/desarrollo/xmippBundleP3/src/scipion-em-xmipp/xmipp3/protocols/protocol_particle_pick_consensus.py", line 175, in _checkNewInput
00025:       fDeps = self.insertNewCoorsSteps(newMics)
00026:     File "/home/pablo/desarrollo/xmippBundleP3/src/scipion-em-xmipp/xmipp3/protocols/protocol_particle_pick_consensus.py", line 133, in insertNewCoorsSteps
00027:       micrograph, prerequisites=[])
00028:     File "/home/pablo/desarrollo/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 986, in _insertFunctionStep
00029:       step = FunctionStep(func, funcName, *funcArgs, **kwargs)
00030:     File "/home/pablo/desarrollo/scipion-pyworkflow/pyworkflow/protocol/protocol.py", line 228, in __init__
00031:       self.argsStr = String(json.dumps(funcArgs))
00032:     File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
00033:       return _default_encoder.encode(obj)
00034:     File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
00035:       chunks = self.iterencode(o, _one_shot=True)
00036:     File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
00037:       return _iterencode(o, 0)
00038:     File "/usr/lib/python3.5/json/encoder.py", line 179, in default
00039:       raise TypeError(repr(o) + " is not JSON serializable")
00040:   TypeError: <pwem.objects.data.Micrograph object at 0x7fbf1b562cc0> is not JSON serializable

We are getting this very often....I guess replacing picke with JSON is not as compatible as we thought.

**Comment by delarosatrevin** [comment]
It seems that a Micrograph object is being passes as input in one step
function, this does not worked with pickled neither.
Our subclasses from Object are not pickle (or json) serializable. (not
right now)

**Comment by pconesa** [comment]
This is fixed in the consensus protocol:
https://github.com/I2PC/scipion-em-xmipp/pull/228
