### ISSUE TITLE
Scipion is not awere of the status of submitted jobs

### ISSUE THREAD

**Issue by JuhaHuiskonen** [scipion-em/scipion-pyworkflow#85]
Sometimes submission of the job to a scheduling system fails (for example when the user asks for more memory than allowed in a particular queue). Scipion shows this job with status "Launched". It would be nice if Scipion kept checking if the job is actually in the queue or not (if it got a job ID or not). If not, it should be marked as "Failed"

**Comment by azazellochg** [comment]
same as #86
