### ISSUE TITLE
Scipion is not awere of the status of submitted jobs

### ISSUE THREAD

**Issue by pconesa** [scipion-em/scipion-pyworkflow#86]
**Migrated from**: https://github.com/I2PC/scipion/issues/2080
**Posted by**: @JuhaHuiskonen 

Sometimes submission of the job to a scheduling system fails (for example when the user asks for more memory than allowed in a particular queue). Scipion shows this job with status "Launched". It would be nice if Scipion kept checking if the job is actually in the queue or not (if it got a job ID or not). If not, it should be marked as "Failed"

**Comment by pconesa** [comment]
@JuhaHuiskonen , are you getting an exit code different than 0 from the declined "qsub" command?

**Comment by azazellochg** [comment]
I can confirm this bug. qsub returns exit code 1 in my case.

**Comment by azazellochg** [comment]
4e7c071 checks return code but the protocol status is still "launched"

**Comment by azazellochg** [comment]
47f7561f609756318ac95a588f30beb6296ae444 should fix this
