### ISSUE TITLE
rename mrc to mrcs

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-pyworkflow#99]
https://github.com/scipion-em/scipion-pyworkflow/blob/04908b0a72ff7cfb2c712786a83b8a1febe4bd6c/pyworkflow/tests/__init__.py#L160

This is the only file in the dataset that is mrc but it's a set of 2D images. This causes relion conversion tests fail. I suggest rename this to mrcs. emx and xmd in the same folder have to be adjusted. Xmipp convert test need to be tested after this change.

**Comment by delarosatrevin** [comment]
We can also create a symlink in the Relion test

**Comment by azazellochg** [comment]
ok
